// Ce fichier est ton "entrepôt" de mots
const dictionnaireGeant = [
    { arabe: "كِتَابٌ", francais: "Livre" },
    { arabe: "قَلَمٌ", francais: "Stylo" },
    { arabe: "مَدْرَسَةٌ", francais: "École" },
    { arabe: "قِرَاءَةٌ", francais: "Lecture" },
    { arabe: "كِتَابَةٌ", francais: "Écriture" },
    { arabe: "مَكْتَبَةٌ", francais: "Bibliothèque" },
    { arabe: "دَفْتَرٌ", francais: "Cahier" },
    { arabe: "أُسْتَاذٌ", francais: "Professeur" },
    { arabe: "طَالِبٌ", francais: "Étudiant" },
    { arabe: "كُرْسِيٌّ", francais: "Chaise" },
    { arabe: "طَاوِلَةٌ", francais: "Table" },
    { arabe: "بَابٌ", francais: "Porte" },
    { arabe: "نَافِذَةٌ", francais: "Fenêtre" },
    { arabe: "حَاسُوبٌ", francais: "Ordinateur" },
    { arabe: "هَاتِفٌ", francais: "Téléphone" },
    { arabe: "سَاعَةٌ", francais: "Horloge" },
    { arabe: "وَرَقَةٌ", francais: "Feuille" },
    { arabe: "مِمْحَاةٌ", francais: "Gomme" },
    { arabe: "مِبْرَاةٌ", francais: "Taille-crayon" },
    { arabe: "حَقِيبَةٌ", francais: "Sac" },
        // --- LES NOMBRES (الأَرْقَام) ---
    { arabe: "وَاحِدٌ", francais: "Un (1)" },
    { arabe: "اِثْنَانِ", francais: "Deux (2)" },
    { arabe: "ثَلَاثَةٌ", francais: "Trois (3)" },
    { arabe: "أَرْبَعَةٌ", francais: "Quatre (4)" },
    { arabe: "خَمْسَةٌ", francais: "Cinq (5)" },
    { arabe: "سِتَّةٌ", francais: "Six (6)" },
    { arabe: "سَبْعَةٌ", francais: "Sept (7)" },
    { arabe: "ثَمَانِيَةٌ", francais: "Huit (8)" },
    { arabe: "تِسْعَةٌ", francais: "Neuf (9)" },
    { arabe: "عَشَرَةٌ", francais: "Dix (10)" },
    // --- LE TEMPS (الْوَقْت) ---
    { arabe: "يَوْمٌ", francais: "Jour" },
    { arabe: "أُسْبُوعٌ", francais: "Semaine" },
    { arabe: "شَهْرٌ", francais: "Mois" },
    { arabe: "سَنَةٌ", francais: "Année" },
    { arabe: "الْيَوْمَ", francais: "Aujourd'hui" },
    { arabe: "أَمْسِ", francais: "Hier" },
    { arabe: "غَداً", francais: "Demain" },
    { arabe: "سَاعَةٌ", francais: "Heure" },
    { arabe: "دَقِيقَةٌ", francais: "Minute" },
    { arabe: "لَحْظَةٌ", francais: "Moment" },
    // --- LA FAMILLE (الْعَائِلَة) ---
    { arabe: "أَبٌ", francais: "Père" },
    { arabe: "أُمٌّ", francais: "Mère" },
    { arabe: "أَخٌ", francais: "Frère" },
    { arabe: "أُخْتٌ", francais: "Sœur" },
    { arabe: "جَدٌّ", francais: "Grand-père" },
    { arabe: "جَدَّةٌ", francais: "Grand-mère" },
    { arabe: "عَمٌّ", francais: "Oncle (paternel)" },
    { arabe: "خَالٌ", francais: "Oncle (maternel)" },
    { arabe: "اِبْنٌ", francais: "Fils" },
    { arabe: "اِبْنَةٌ", francais: "Fille (enfant)" },
    // --- LA MAISON (الْبَيْت) ---
    { arabe: "بَابٌ", francais: "Porte" },
    { arabe: "نَافِذَةٌ", francais: "Fenêtre" },
    { arabe: "غُرْفَةٌ", francais: "Chambre" },
    { arabe: "مَطْبَخٌ", francais: "Cuisine" },
    { arabe: "حَمَّامٌ", francais: "Salle de bain" },
    { arabe: "سَرِيرٌ", francais: "Lit" },
    { arabe: "مِرْآةٌ", francais: "Miroir" },
    { arabe: "سَطْحٌ", francais: "Toit" },
    { arabe: "جِدَارٌ", francais: "Mur" },
    { arabe: "مِفْتَاحٌ", francais: "Clé" },
    // --- LA NATURE (الطَّبِيعَة) ---
    { arabe: "سَمَاءٌ", francais: "Ciel" },
    { arabe: "أَرْضٌ", francais: "Terre" },
    { arabe: "بَحْرٌ", francais: "Mer" },
    { arabe: "نَهْرٌ", francais: "Rivière" },
    { arabe: "جَبَلٌ", francais: "Montagne" },
    { arabe: "شَجَرَةٌ", francais: "Arbre" },
    { arabe: "زَهْرَةٌ", francais: "Fleur" },
    { arabe: "مَطَرٌ", francais: "Pluie" },
    { arabe: "ثَلْجٌ", francais: "Neige" },
    { arabe: "رِيحٌ", francais: "Vent" },
    // --- LE CORPS HUMAIN (جِسْمُ الْإِنْسَان) ---
    { arabe: "رَأْسٌ", francais: "Tête" },
    { arabe: "وَجْهٌ", francais: "Visage" },
    { arabe: "عَيْنٌ", francais: "Œil" },
    { arabe: "أُذُنٌ", francais: "Oreille" },
    { arabe: "أَنْفٌ", francais: "Nez" },
    { arabe: "فَمٌ", francais: "Bouche" },
    { arabe: "لِسَانٌ", francais: "Langue" },
    { arabe: "يَدٌ", francais: "Main" },
    { arabe: "رِجْلٌ", francais: "Jambe/Pied" },
    { arabe: "قَلْبٌ", francais: "Cœur" },
    // --- NOURRITURE ET BOISSON (الطَّعَام وَالشَّرَاب) ---
    { arabe: "مَاءٌ", francais: "Eau" },
    { arabe: "حَلِيبٌ", francais: "Lait" },
    { arabe: "عَصِيرٌ", francais: "Jus" },
    { arabe: "خُبْزٌ", francais: "Pain" },
    { arabe: "أَرُزٌّ", francais: "Riz" },
    { arabe: "دَجَاجٌ", francais: "Poulet" },
    { arabe: "سَمَكٌ", francais: "Poisson" },
    { arabe: "فَاكِهَةٌ", francais: "Fruit" },
    { arabe: "خُضَارٌ", francais: "Légumes" },
    { arabe: "مِلْحٌ", francais: "Sel" },
    // --- VERBES COURANTS (أَفْعَال شَائِعَة) ---
    { arabe: "أَكَلَ", francais: "Manger" },
    { arabe: "شَرِبَ", francais: "Boire" },
    { arabe: "نَامَ", francais: "Dormir" },
    { arabe: "ذَهَبَ", francais: "Aller" },
    { arabe: "جَاءَ", francais: "Venir" },
    { arabe: "قَرَأَ", francais: "Lire" },
    { arabe: "كَتَبَ", francais: "Écrire" },
    { arabe: "فَهِمَ", francais: "Comprendre" },
    { arabe: "عَرَفَ", francais: "Savoir" },
    { arabe: "قَالَ", francais: "Dire" },
    // --- QUALITÉS ET ADJECTIFS (صِفَات) ---
    { arabe: "جَدِيدٌ", francais: "Nouveau" },
    { arabe: "قَدِيمٌ", francais: "Ancien" },
    { arabe: "قَوِيٌّ", francais: "Fort" },
    { arabe: "ضَعِيفٌ", francais: "Faible" },
    { arabe: "سَرِيعٌ", francais: "Rapide" },
    { arabe: "بَطِيءٌ", francais: "Lent" },
    { arabe: "طَوِيلٌ", francais: "Long / Grand" },
    { arabe: "قَصِيرٌ", francais: "Court" },
    { arabe: "غَنِيٌّ", francais: "Riche" },
    { arabe: "فَقِيرٌ", francais: "Pauvre" },
    // --- L'ÉCOLE (الْمَدْرَسَة) ---
    { arabe: "قَلَمٌ", francais: "Stylo" },
    { arabe: "مِحْفَظَةٌ", francais: "Cartable" },
    { arabe: "سَبُّورَةٌ", francais: "Tableau" },
    { arabe: "اِمْتِحَانٌ", francais: "Examen" },
    { arabe: "دَرْسٌ", francais: "Leçon" },
    { arabe: "فَصْلٌ", francais: "Classe" },
    { arabe: "مُدِيرٌ", francais: "Directeur" },
    { arabe: "مَقْعَدٌ", francais: "Banc / Siège" },
    { arabe: "مَكْتَبٌ", francais: "Bureau" },
    { arabe: "خَرِيطَةٌ", francais: "Carte (géographique)" },
    // --- LES ANIMAUX (الْحَيَوَانَات) ---
    { arabe: "كَلْبٌ", francais: "Chien" },
    { arabe: "قِطٌّ", francais: "Chat" },
    { arabe: "حِصَانٌ", francais: "Cheval" },
    { arabe: "جَمَلٌ", francais: "Chameau" },
    { arabe: "أَسَدٌ", francais: "Lion" },
    { arabe: "فِيلٌ", francais: "Éléphant" },
    { arabe: "قِرْدٌ", francais: "Singe" },
    { arabe: "عُصْفُورٌ", francais: "Oiseau / Moineau" },
    { arabe: "دَجَاجَةٌ", francais: "Poule" },
    { arabe: "بَقَرَةٌ", francais: "Vache" },
    { arabe: "خَرُوفٌ", francais: "Mouton" },
    { arabe: "أَرْنَبٌ", francais: "Lapin" },
    { arabe: "نَمِرٌ", francais: "Tigre" },
    { arabe: "ثُعْبَانٌ", francais: "Serpent" },
    { arabe: "نَحْلَةٌ", francais: "Abeille" },
    { arabe: "نَمْلَةٌ", francais: "Fourmi" },
    { arabe: "فَرَاشَةٌ", francais: "Papillon" },
    { arabe: "تِمْسَاحٌ", francais: "Crocodile" },
    { arabe: "سُلَحْفَاةٌ", francais: "Tortue" },
    { arabe: "ذِئْبٌ", francais: "Loup" },
    // --- LES MÉTIERS (الْمِهَن) ---
    { arabe: "طَبِيبٌ", francais: "Médecin" },
    { arabe: "مُمَرِّضٌ", francais: "Infirmier" },
    { arabe: "مُهَنْدِسٌ", francais: "Ingénieur" },
    { arabe: "طَيَّارٌ", francais: "Pilote" },
    { arabe: "شُرْطِيٌّ", francais: "Policier" },
    { arabe: "طَبَّاخٌ", francais: "Cuisinier" },
    { arabe: "فَلَّاحٌ", francais: "Agriculteur" },
    { arabe: "نَجَّارٌ", francais: "Menuisier" },
    { arabe: "خَيَّاطٌ", francais: "Tailleur" },
    { arabe: "حَلَّاقٌ", francais: "Coiffeur" },
    { arabe: "سَائِقٌ", francais: "Chauffeur" },
    { arabe: "تَاجِرٌ", francais: "Marchand / Commerçant" },
    { arabe: "جُنْدِيٌّ", francais: "Soldat" },
    { arabe: "مُحَامٍ", francais: "Avocat" },
    { arabe: "قَاضٍ", francais: "Juge" },
    { arabe: "رَسَّامٌ", francais: "Peintre" },
    { arabe: "مُغَنٍّ", francais: "Chanteur" },
    { arabe: "مُذِيعٌ", francais: "Présentateur" },
    { arabe: "صَحَفِيٌّ", francais: "Journaliste" },
    { arabe: "عَامِلٌ", francais: "Ouvrier" },
    // --- LES VÊTEMENTS (الْمَلَابِس) ---
    { arabe: "قَمِيصٌ", francais: "Chemise" },
    { arabe: "سِرْوَالٌ", francais: "Pantalon" },
    { arabe: "فُسْتَانٌ", francais: "Robe" },
    { arabe: "مِعْطَفٌ", francais: "Manteau" },
    { arabe: "حِذَاءٌ", francais: "Chaussure" },
    { arabe: "جَوْرَبٌ", francais: "Chaussette" },
    { arabe: "قُبَّعَةٌ", francais: "Chapeau" },
    { arabe: "نَظَّارَةٌ", francais: "Lunettes" },
    { arabe: "حِزَامٌ", francais: "Ceinture" },
    { arabe: "وِشَاحٌ", francais: "Écharpe" },
    // --- LES ÉMOTIONS ET ÉTATS (الشُّعُور وَالْحَال) ---
    { arabe: "جَوْعَانٌ", francais: "Affamé" },
    { arabe: "عَطْشَانٌ", francais: "Assoiffé" },
    { arabe: "تَعْبَانٌ", francais: "Fatigué" },
    { arabe: "نَعْسَانٌ", francais: "Envie de dormir" },
    { arabe: "مَشْغُولٌ", francais: "Occupé" },
// --- VERBES DE MOUVEMENT ET ACTION (أَفْعَالُ الْحَرَكَةِ) ---
    { arabe: "جَلَسَ", francais: "S'asseoir" },
    { arabe: "قَامَ", francais: "Se lever" },
    { arabe: "دَخَلَ", francais: "Entrer" },
    { arabe: "خَرَجَ", francais: "Sortir" },
    { arabe: "رَكَدَ", francais: "Courir" },
    { arabe: "مَشَى", francais: "Marcher" },
    { arabe: "سَبَحَ", francais: "Nager" },
    { arabe: "طَارَ", francais: "Voler" },
    { arabe: "رَكِبَ", francais: "Monter (véhicule/animal)" },
    { arabe: "نَزَلَ", francais: "Descendre" },
    { arabe: "فَتَحَ", francais: "Ouvrir" },
    { arabe: "أَغْلَقَ", francais: "Fermer" },
    { arabe: "كَسَرَ", francais: "Casser" },
    { arabe: "صَلَحَ", francais: "Réparer" },
    { arabe: "نَظَّفَ", francais: "Nettoyer" },
    { arabe: "غَسَلَ", francais: "Laver" },
    { arabe: "طَبَخَ", francais: "Cuisiner" },
    { arabe: "اشْتَرَى", francais: "Acheter" },
    { arabe: "بَاعَ", francais: "Vendre" },
    { arabe: "أَعْطَى", francais: "Donner" },
    // --- DANS LA CUISINE (فِي الْمَطْبَخِ) ---
    { arabe: "صَحْنٌ", francais: "Assiette" },
    { arabe: "كُوبٌ", francais: "Verre / Tasse" },
    { arabe: "مِلْعَقَةٌ", francais: "Cuillère" },
    { arabe: "شَوْكَةٌ", francais: "Fourchette" },
    { arabe: "سِكِّينٌ", francais: "Couteau" },
    { arabe: "قِدْرٌ", francais: "Marmite / Casserole" },
    { arabe: "مِقْلَاةٌ", francais: "Poêle" },
    { arabe: "ثَلَّاجَةٌ", francais: "Réfrigérateur" },
    { arabe: "فُرْنٌ", francais: "Four" },
    { arabe: "مَوْقِدٌ", francais: "Cuisinière / Plaque" },
    // --- PHÉNOMÈNES ET PAYSAGES (الظَّوَاهِرُ وَالْمَنَاظِرُ) ---
    { arabe: "غَابَةٌ", francais: "Forêt" },
    { arabe: "صَحْرَاءُ", francais: "Désert" },
    { arabe: "جَزِيرَةٌ", francais: "Île" },
    { arabe: "شَلَّالٌ", francais: "Cascade" },
    { arabe: "كَهْفٌ", francais: "Grotte" },
    { arabe: "شَاطِئٌ", francais: "Plage" },
    { arabe: "أَمْوَاجٌ", francais: "Vagues" },
    { arabe: "زِلْزَالٌ", francais: "Tremblement de terre" },
    { arabe: "بُرْكَانٌ", francais: "Volcan" },
    { arabe: "ضَبَابٌ", francais: "Brouillard" },
    // --- ADJECTIFS DE PERSONNALITÉ (الصِّفَاتُ الشَّخْصِيَّةُ) ---
    { arabe: "ذَكِيٌّ", francais: "Intelligent" },
    { arabe: "غَبِيٌّ", francais: "Stupide" },
    { arabe: "كَرِيمٌ", francais: "Généreux" },
    { arabe: "بَخِيلٌ", francais: "Avare" },
    { arabe: "شُجَاعٌ", francais: "Courageux" },
    { arabe: "جَبَانٌ", francais: "Lâche / Peureux" },
    { arabe: "صَادِقٌ", francais: "Honnête / Sincère" },
    { arabe: "كَاذِبٌ", francais: "Menteur" },
    { arabe: "مُجْتَهِدٌ", francais: "Travailleur" },
    { arabe: "كَسْلَانُ", francais: "Paresseux" },
    { arabe: "لَطِيفٌ", francais: "Gentil" },
    { arabe: "مُؤَدَّبٌ", francais: "Poli" },
    { arabe: "مَشْهُورٌ", francais: "Célèbre" },
    { arabe: "مَجْنُونٌ", francais: "Fou" },
    { arabe: "عَاقِلٌ", francais: "Sage / Raisonnable" },
    // --- OBJETS DU SALON ET BUREAU (أَثَاثٌ) ---
    { arabe: "أَرِيكَةٌ", francais: "Canapé" },
    { arabe: "سِجَّادَةٌ", francais: "Tapis" },
    { arabe: "تِلْفَازٌ", francais: "Télévision" },
    { arabe: "صُورَةٌ", francais: "Image / Photo" },
    { arabe: "رَفٌّ", francais: "Étagère" },
    { arabe: "مِصْبَاحٌ", francais: "Lampe" },
    { arabe: "مِكْيَافٌ", francais: "Climatiseur" },
    { arabe: "سَلَّةُ نِفَايَاتٍ", francais: "Poubelle" },
    { arabe: "جَرَسٌ", francais: "Cloche / Sonnette" },
    { arabe: "سِتَارَةٌ", francais: "Rideau" },
// --- SPIRITUALITÉ ET ISLAM (الإِسْلَامُ وَالرُّوحَانِيَّاتُ) ---
    { arabe: "اللهُ", francais: "Allah (Dieu)" },
    { arabe: "رَسُولٌ", francais: "Messager" },
    { arabe: "نَبِيٌّ", francais: "Prophète" },
    { arabe: "قُرْآنٌ", francais: "Coran" },
    { arabe: "إِيمَانٌ", francais: "Foi" },
    { arabe: "صَلَاةٌ", francais: "Prière" },
    { arabe: "صَوْمٌ", francais: "Jeûne" },
    { arabe: "زَكَاةٌ", francais: "Aumône légale" },
    { arabe: "حَجٌّ", francais: "Pèlerinage" },
    { arabe: "دُعَاءٌ", francais: "Invocation" },
    { arabe: "جَنَّةٌ", francais: "Paradis" },
    { arabe: "نَارٌ", francais: "Enfer" },
    { arabe: "مَلَائِكَةٌ", francais: "Anges" },
    { arabe: "مَسْجِدٌ", francais: "Mosquée" },
    { arabe: "أَذَانٌ", francais: "Appel à la prière" },
    { arabe: "وُضُوءٌ", francais: "Ablutions" },
    { arabe: "ثَوَابٌ", francais: "Récompense divine" },
    { arabe: "ذَنْبٌ", francais: "Péché" },
    { arabe: "تَوْبَةٌ", francais: "Repentir" },
    { arabe: "خَالِقٌ", francais: "Créateur" },
    // --- LES SPORTS (الرِّيَاضَةُ) ---
    { arabe: "كُرَةُ الْقَدَمِ", francais: "Football" },
    { arabe: "كُرَةُ السَّلَّةِ", francais: "Basketball" },
    { arabe: "السِّبَاحَةُ", francais: "Natation" },
    { arabe: "الْجَرْيُ", francais: "Course à pied" },
    { arabe: "الْمُلَاكَمَةُ", francais: "Boxe" },
    { arabe: "الرِّمَايَةُ", francais: "Tir à l'arc" },
    { arabe: "فُرُوسِيَّةٌ", francais: "Équitation" },
    { arabe: "دَرَّاجَةٌ", francais: "Vélo" },
    { arabe: "مَلْعَبٌ", francais: "Stade / Terrain" },
    { arabe: "فَرِيقٌ", francais: "Équipe" },
    // --- INSTRUMENTS ET DIVERTISSEMENT (الْمُوسِيقَى وَالتَّرْفِيهُ) ---
    { arabe: "عُودٌ", francais: "Oud (Luth)" },
    { arabe: "طَبْلٌ", francais: "Tambour" },
    { arabe: "نَايٌ", francais: "Flûte" },
    { arabe: "قِيثَارَةٌ", francais: "Guitare" },
    { arabe: "صَوْتٌ", francais: "Son / Voix" },
    { arabe: "لُعْبَةٌ", francais: "Jouet / Jeu" },
    { arabe: "دُمْيَةٌ", francais: "Poupée" },
    { arabe: "مَسْرَحٌ", francais: "Théâtre" },
    { arabe: "سِينِمَا", francais: "Cinéma" },
    { arabe: "رِحْلَةٌ", francais: "Voyage / Excursion" },
    // --- BRICOLAGE ET OUTILS (الْعَمَلُ وَالْأَدَوَاتُ) ---
    { arabe: "مِطْرَقَةٌ", francais: "Marteau" },
    { arabe: "مِسْمَارٌ", francais: "Clou" },
    { arabe: "مِفَكٌّ", francais: "Tournevis" },
    { arabe: "مِنْشَارٌ", francais: "Scie" },
    { arabe: "سُلَّمٌ", francais: "Échelle" },
    { arabe: "دِهَانٌ", francais: "Peinture (matière)" },
    { arabe: "خَشَبٌ", francais: "Bois" },
    { arabe: "حَدِيدٌ", francais: "Fer" },
    { arabe: "زُجَاجٌ", francais: "Verre (matière)" },
    { arabe: "بِلَاسْتِيكٌ", francais: "Plastique" },
    // --- GÉOGRAPHIE ET ESPACE (الْجُغْرَافِيَا وَالْفَضَاءُ) ---
    { arabe: "كَوْكَبٌ", francais: "Planète" },
    { arabe: "نَجْمٌ", francais: "Étoile" },
    { arabe: "قَارَّةٌ", francais: "Continent" },
    { arabe: "دَوْلَةٌ", francais: "Pays / État" },
    { arabe: "عَاصِمَةٌ", francais: "Capitale" },
    { arabe: "حُدُودٌ", francais: "Frontières" },
    { arabe: "عَلَمٌ", francais: "Drapeau" },
    { arabe: "خَرِيَطَةٌ", francais: "Carte" },
    { arabe: "شَمَالٌ", francais: "Nord" },
    { arabe: "جَنُوبٌ", francais: "Sud" },
    { arabe: "شَرْقٌ", francais: "Est" },
    { arabe: "غَرْبٌ", francais: "Ouest" },
    // --- TECHNOLOGIE ET INTERNET (التِّكْنُولُوجِيَا وَالإِنْتِرْنِت) ---
    { arabe: "شَاشَةٌ", francais: "Écran" },
    { arabe: "لَوْحَةُ مَفَاتِيحَ", francais: "Clavier" },
    { arabe: "فَأْرَةٌ", francais: "Souris (informatique)" },
    { arabe: "رَابِطٌ", francais: "Lien / URL" },
    { arabe: "مَوْقِعٌ", francais: "Site web" },
    { arabe: "بَرِيدٌ إِلِكْتُرُونِيٌّ", francais: "E-mail" },
    { arabe: "رِسَالَةٌ", francais: "Message" },
    { arabe: "تَطْبِيقٌ", francais: "Application" },
    { arabe: "مَلَفٌّ", francais: "Fichier / Dossier" },
    { arabe: "شَاحِنٌ", francais: "Chargeur" },
    { arabe: "بَطَّارِيَّةٌ", francais: "Batterie" },
    { arabe: "رَقْمٌ سِرِّيٌّ", francais: "Mot de passe" },
    // --- GOÛTS ET ÉPICES (النَّكَهَاتُ وَالتَّوَابِلُ) ---
    { arabe: "حُلْوٌ", francais: "Sucré" },
    { arabe: "مُرٌّ", francais: "Amer" },
    { arabe: "حَامِضٌ", francais: "Acide / Citronné" },
    { arabe: "حَارٌّ", francais: "Piquant / Épicé" },
    { arabe: "لَذِيذٌ", francais: "Délicieux" },
    { arabe: "فِلْفِلٌ", francais: "Poivre" },
    { arabe: "كَمُّونٌ", francais: "Cumin" },
    { arabe: "قِرْفَةٌ", francais: "Cannelle" },
    { arabe: "زَنْجَبِيلٌ", francais: "Gingembre" },
    { arabe: "زَعْتَرٌ", francais: "Thym" },
    { arabe: "نَعْنَاعٌ", francais: "Menthe" },
    { arabe: "عَسَلٌ", francais: "Miel" },
    // --- SANTÉ ET CORPS (الصِّحَّةُ وَالْجِسْمُ) ---
    { arabe: "دَوَاءٌ", francais: "Médicament" },
    { arabe: "صَيْدَلِيٌّ", francais: "Pharmacien" },
    { arabe: "أَلَمٌ", francais: "Douleur" },
    { arabe: "صُدَاعٌ", francais: "Mal de tête" },
    { arabe: "زُكَامٌ", francais: "Rhume" },
    { arabe: "سُعَالٌ", francais: "Toux" },
    { arabe: "حُمَّى", francais: "Fièvre" },
    { arabe: "جُرْحٌ", francais: "Blessure" },
    { arabe: "دَمٌ", francais: "Sang" },
    { arabe: "قَلْبٌ", francais: "Cœur" },
    { arabe: "عَظْمٌ", francais: "Os" },
    { arabe: "رِئَةٌ", francais: "Poumon" },
    // --- MÉTÉO ET SAISONS (الطَّقْسُ وَالْفُصُولُ) ---
    { arabe: "الرَّبِيعُ", francais: "Le Printemps" },
    { arabe: "الصَّيْفُ", francais: "L'Été" },
    { arabe: "الْخَرِيفُ", francais: "L'Automne" },
    { arabe: "الشِّتَاءُ", francais: "L'Hiver" },
    { arabe: "جَوٌّ", francais: "Atmosphère / Climat" },
    { arabe: "غَيْمٌ", francais: "Nuage" },
    { arabe: "رَعْدٌ", francais: "Tonnerre" },
    { arabe: "بَرْقٌ", francais: "Éclair" },
    { arabe: "رُطُوبَةٌ", francais: "Humidité" },
    { arabe: "شَمْسِيٌّ", francais: "Ensoleillé" },
    // --- ACCESSOIRES ET VÊTEMENTS (تَتِمَّةُ الْمَلَابِسِ) ---
    { arabe: "مِظَلَّةٌ", francais: "Parapluie" },
    { arabe: "خَاتَمٌ", francais: "Bague" },
    { arabe: "سِوَارٌ", francais: "Bracelet" },
    { arabe: "عِقْدٌ", francais: "Collier" },
    { arabe: "مِحْفَظَةٌ", francais: "Portefeuille" },
    { arabe: "جَيْبٌ", francais: "Poche" },
    { arabe: "زِرٌّ", francais: "Bouton" },
    { arabe: "قُمَاشٌ", francais: "Tissu" },
    { arabe: "حَرِيرٌ", francais: "Soie" },
    { arabe: "قُطْنٌ", francais: "Coton" },
    { arabe: "صُوفٌ", francais: "Laine" },
    // --- VOYAGE ET DÉPLACEMENT (السَّفَرُ وَالتَّنَقُّلُ) ---
    { arabe: "جَوَازُ سَفَرٍ", francais: "Passeport" },
    { arabe: "تَذْكِرَةٌ", francais: "Billet / Ticket" },
    { arabe: "حَقِيبَةُ سَفَرٍ", francais: "Valise" },
    { arabe: "فِيزَا", francais: "Visa" },
    { arabe: "تَفْتِيشٌ", francais: "Contrôle / Fouille" },
    { arabe: "بَوَّابَةٌ", francais: "Porte d'embarquement" },
    { arabe: "مَوْعِدٌ", francais: "Rendez-vous / Horaire" },
    { arabe: "تَأْخِيرٌ", francais: "Retard" },
    { arabe: "مَعْلُومَاتٌ", francais: "Informations" },
    { arabe: "سِيَاحَةٌ", francais: "Tourisme" },
    // --- ADVERBES DE TEMPS ET LIEU (ظُرُوفُ الزَّمَانِ وَالْمَكَانِ) ---
    { arabe: "هُنَا", francais: "Ici" },
    { arabe: "هُنَاكَ", francais: "Là-bas" },
    { arabe: "الآنَ", francais: "Maintenant" },
    { arabe: "قَبْلُ", francais: "Avant" },
    { arabe: "بَعْدُ", francais: "Après" },
    { arabe: "دَائِماً", francais: "Toujours" },
    { arabe: "أَبَداً", francais: "Jamais" },
    { arabe: "أَحْيَاناً", francais: "Parfois" },
    { arabe: "فَوْقَ", francais: "Au-dessus / Sur" },
    { arabe: "تَحْتَ", francais: "Au-dessous / Sous" },
    { arabe: "أَمَامَ", francais: "Devant" },
    { arabe: "خَلْفَ", francais: "Derrière" },
    { arabe: "بَيْنَ", francais: "Entre" },
    { arabe: "جَانِبَ", francais: "À côté de" },
    // --- JUSTICE ET SOCIÉTÉ (الْعَدْلُ وَالْمُجْتَمَعُ) ---
    { arabe: "قَانُونٌ", francais: "Loi" },
    { arabe: "حَقٌّ", francais: "Droit" },
    { arabe: "حُرِّيَّةٌ", francais: "Liberté" },
    { arabe: "سَلَامٌ", francais: "Paix" },
    { arabe: "حَرْبٌ", francais: "Guerre" },
    { arabe: "جَرِيمَةٌ", francais: "Crime" },
    { arabe: "سِجْنٌ", francais: "Prison" },
    { arabe: "شَاهِدٌ", francais: "Témoin" },
    { arabe: "أَمْنٌ", francais: "Sécurité" },
    { arabe: "حُكُومَةٌ", francais: "Gouvernement" },
    { arabe: "رَئِيسٌ", francais: "Président" },
    { arabe: "شَعْبٌ", francais: "Peuple" },
    // --- PETITES BÊTES ET INSECTES (حَشَرَاتٌ) ---
    { arabe: "ذُبَابَةٌ", francais: "Mouche" },
    { arabe: "بَعُوضَةٌ", francais: "Moustique" },
    { arabe: "عَنْكَبُوتٌ", francais: "Araignée" },
    { arabe: "صُرْصُورٌ", francais: "Cafard" },
    { arabe: "دُودَةٌ", francais: "Ver" },
    { arabe: "عَقْرَبٌ", francais: "Scorpion" },
    // --- MATÉRIAUX ET FORMES (مَوَادُّ وَأَشْكَالٌ) ---
    { arabe: "دَائِرَةٌ", francais: "Cercle" },
    { arabe: "مُرَبَّعٌ", francais: "Carré" },
    { arabe: "مُثَلَّثٌ", francais: "Triangle" },
    { arabe: "خَطٌّ", francais: "Ligne" },
    { arabe: "نُقْطَةٌ", francais: "Point" },
    { arabe: "ذَهَبٌ", francais: "Or" },
    { arabe: "فِضَّةٌ", francais: "Argent (métal)" },
    { arabe: "نُحَاسٌ", francais: "Cuivre" },
    { arabe: "حَجَرٌ", francais: "Pierre" },
    { arabe: "رَمْلٌ", francais: "Sable" },
    // --- MOTS DE LIAISON ET QUESTIONS (أَدَوَاتُ الِاسْتِفْهَامِ وَالرَّبْطِ) ---
    { arabe: "مَنْ؟", francais: "Qui ?" },
    { arabe: "مَاذَا؟", francais: "Quoi ?" },
    { arabe: "لِمَاذَا؟", francais: "Pourquoi ?" },
    { arabe: "كَيْفَ؟", francais: "Comment ?" },
    { arabe: "مَتَى؟", francais: "Quand ?" },
    { arabe: "أَيْنَ؟", francais: "Où ?" },
    { arabe: "كَمْ؟", francais: "Combien ?" },
    { arabe: "أَيُّ؟", francais: "Quel / Lequel ?" },
    { arabe: "لِأَنَّ", francais: "Parce que" },
    { arabe: "لَكِنَّ", francais: "Mais" },
    { arabe: "أَيْضاً", francais: "Aussi" },
    { arabe: "فَقَطْ", francais: "Seulement" },
// --- DÉTAILS DE LA MAISON (تَفَاصِيلُ الْمَنْزِلِ) ---
    { arabe: "سُلَّمٌ", francais: "Escalier" },
    { arabe: "شُرْفَةٌ", francais: "Balcon" },
    { arabe: "مَمَرٌّ", francais: "Couloir" },
    { arabe: "قَبْوٌ", francais: "Cave" },
    { arabe: "سَقْفٌ", francais: "Plafond" },
    { arabe: "أَرْضِيَّةٌ", francais: "Sol" },
    { arabe: "مِصْعَدٌ", francais: "Ascenseur" },
    { arabe: "مَدْخَلٌ", francais: "Entrée" },
    { arabe: "جَرَسٌ", francais: "Sonnette" },
    { arabe: "قُفْلٌ", francais: "Serrure" },
    // --- COMMERCE ET ARGENT (التِّجَارَةُ وَالْمَالُ) ---
    { arabe: "مَصْرِفٌ / بَنْكٌ", francais: "Banque" },
    { arabe: "نُقُودٌ", francais: "Argent (monnaie)" },
    { arabe: "سِعْرٌ / ثَمَنٌ", francais: "Prix" },
    { arabe: "فَاتُورَةٌ", francais: "Facture" },
    { arabe: "بِطَاقَةٌ بَنْكِيَّةٌ", francais: "Carte bancaire" },
    { arabe: "تَخْفِيضٌ", francais: "Réduction / Solde" },
    { arabe: "مَجَّانِيٌّ", francais: "Gratuit" },
    { arabe: "غَالٍ", francais: "Cher" },
    { arabe: "رَخِيصٌ", francais: "Bon marché" },
    { arabe: "دَيْنٌ", francais: "Dette" },
    { arabe: "رِبْحٌ", francais: "Profit / Gain" },
    { arabe: "خَسَارَةٌ", francais: "Perte" },
    // --- VERBES DE COMMUNICATION (أَفْعَالُ التَّوَاصُلِ) ---
    { arabe: "اتَّصَلَ", francais: "Appeler / Contacter" },
    { arabe: "صَرَخَ", francais: "Crier" },
    { arabe: "هَمَسَ", francais: "Chuchoter" },
    { arabe: "وَعَدَ", francais: "Promettre" },
    { arabe: "حَكَى", francais: "Raconter" },
    { arabe: "سَأَلَ", francais: "Demander / Questionner" },
    { arabe: "أَجَابَ", francais: "Répondre" },
    { arabe: "شَرَحَ", francais: "Expliquer" },
    { arabe: "نَصَحَ", francais: "Conseiller" },
    { arabe: "حَذَّرَ", francais: "Avertir" },
    // --- ANATOMIE INTERNE (أَعْضَاءُ الْجِسْمِ الدَّاخِلِيَّةُ) ---
    { arabe: "دِمَاغٌ", francais: "Cerveau" },
    { arabe: "مَعِدَةٌ", francais: "Estomac" },
    { arabe: "كَبِدٌ", francais: "Foie" },
    { arabe: "عَضَلَةٌ", francais: "Muscle" },
    { arabe: "عَصَبٌ", francais: "Nerf" },
    { arabe: "عِرْقٌ", francais: "Veine" },
    { arabe: "جُمْجُمَةٌ", francais: "Crâne" },
    { arabe: "هَيْكَلٌ عَظْمِيٌّ", francais: "Squelette" },
    { arabe: "نَفَسٌ", francais: "Souffle / Respiration" },
    { arabe: "حَلْقٌ", francais: "Gorge" },
    // --- TEMPS ET CALENDRIER (الزَّمَانُ وَالتَّقْوِيمُ) ---
    { arabe: "فَجْرٌ", francais: "Aube" },
    { arabe: "ظُهْرٌ", francais: "Midi" },
    { arabe: "عَصْرٌ", francais: "Après-midi" },
    { arabe: "مَغْرِبٌ", francais: "Coucher du soleil" },
    { arabe: "عِشَاءٌ", francais: "Soir / Nuit" },
    { arabe: "مُنْتَصَفُ اللَّيْلِ", francais: "Minuit" },
    { arabe: "بَاكِراً", francais: "Tôt" },
    { arabe: "مُتَأَخِّراً", francais: "Tard" },
    { arabe: "فَوْراً", francais: "Immédiatement" },
    { arabe: "قَرِيباً", francais: "Bientôt" },
    // --- ENVIRONNEMENT URBAIN (الْمُحِيطُ الْعُمْرَانِيُّ) ---
    { arabe: "رَصِيفٌ", francais: "Trottoir" },
    { arabe: "إِشَارَةُ مُرُورٍ", francais: "Feu de signalisation" },
    { arabe: "نَفَقٌ", francais: "Tunnel" },
    { arabe: "عِمَارَةٌ", francais: "Immeuble" },
    { arabe: "حَيٌّ", francais: "Quartier" },
    { arabe: "قَرْيَةٌ", francais: "Village" },
    { arabe: "بَلَدِيَّةٌ", francais: "Mairie" },
    { arabe: "مَرْكَزُ شُرْطَةٍ", francais: "Commissariat" },
// --- BUREAU ET INFORMATIQUE DÉTAILLÉS (الْمَكْتَبُ وَالتِّكْنُولُوجِيَا) ---
    { arabe: "طَابِعَةٌ", francais: "Imprimante" },
    { arabe: "مَاسِحٌ ضَوْئِيٌّ", francais: "Scanner" },
    { arabe: "بَرْنَامَجٌ", francais: "Logiciel / Programme" },
    { arabe: "تَحْدِيثٌ", francais: "Mise à jour" },
    { arabe: "تَحْمِيلٌ", francais: "Téléchargement" },
    { arabe: "ذَاكِرَةٌ", francais: "Mémoire" },
    { arabe: "قُرْصٌ صَلْبٌ", francais: "Disque dur" },
    { arabe: "خَادِمٌ", francais: "Serveur" },
    { arabe: "لَوْحَةٌ رَقْمِيَّةٌ", francais: "Tablette" },
    { arabe: "سَمَّاعَاتٌ", francais: "Écouteurs / Casque" },
    // --- ALIMENTS SECS ET INGRÉDIENTS (مَوَادُّ غِذَائِيَّةٌ) ---
    { arabe: "دَقِيقٌ", francais: "Farine" },
    { arabe: "زَيْتٌ", francais: "Huile" },
    { arabe: "خَلٌّ", francais: "Vinaigre" },
    { arabe: "عَدَسٌ", francais: "Lentilles" },
    { arabe: "حِمُّصٌ", francais: "Pois chiches" },
    { arabe: "مَكَرُونَةٌ", francais: "Pâtes" },
    { arabe: "بَيْضٌ", francais: "Œufs" },
    { arabe: "زُبْدَةٌ", francais: "Beurre" },
    { arabe: "جُبْنٌ", francais: "Fromage" },
    { arabe: "مُرَبَّى", francais: "Confiture" },
    // --- ÉMOTIONS COMPLEXES (مَشَاعِرُ مُعَقَّدَةٌ) ---
    { arabe: "غَيْرَةٌ", francais: "Jalousie" },
    { arabe: "فَخْرٌ", francais: "Fierté" },
    { arabe: "حَنِينٌ", francais: "Nostalgie" },
    { arabe: "وِحْدَةٌ", francais: "Solitude" },
    { arabe: "قَلَقٌ", francais: "Anxiété / Inquiétude" },
    { arabe: "أَمَلٌ", francais: "Espoir" },
    { arabe: "ثِقَةٌ", francais: "Confiance" },
    { arabe: "صَبْرٌ", francais: "Patience" },
    { arabe: "نَدَمٌ", francais: "Regret" },
    { arabe: "تَسَامُحٌ", francais: "Tolérance / Pardon" },
    // --- VERBES D'ÉTAT ET DE PENSÉE (أَفْعَالُ الذِّهْنِ وَالْحَالِ) ---
    { arabe: "بَدَا", francais: "Sembler / Paraître" },
    { arabe: "أَصْبَحَ", francais: "Devenir" },
    { arabe: "بَقِيَ", francais: "Rester" },
    { arabe: "وُجِدَ", francais: "Exister / Se trouver" },
    { arabe: "ظَنَّ", francais: "Penser / Croire" },
    { arabe: "تَذَكَّرَ", francais: "Se souvenir" },
    { arabe: "نَسِيَ", francais: "Oublier" },
    { arabe: "تَمَنَّى", francais: "Souhaiter" },
    { arabe: "قَرَّرَ", francais: "Décider" },
    { arabe: "حَاوَلَ", francais: "Essayer" },
    // --- NATURE ET ASTRONOMIE (الطَّبِيعَةُ وَالْفَلَكُ) ---
    { arabe: "فَضَاءٌ", francais: "Espace" },
    { arabe: "مَجَرَّةٌ", francais: "Galaxie" },
    { arabe: "كُسُوفٌ", francais: "Éclipse" },
    { arabe: "مُحِيطٌ", francais: "Océan" },
    { arabe: "غَابَةٌ مَطِيرَةٌ", francais: "Forêt tropicale" },
    { arabe: "تُرَابٌ", francais: "Poussière / Sol" },
    { arabe: "مَعْدِنٌ", francais: "Métal / Minerai" },
    { arabe: "طَاقَةٌ", francais: "Énergie" },
    { arabe: "كَهْرُبَاءٌ", francais: "Électricité" },
    { arabe: "بِيئَةٌ", francais: "Environnement" },
    // --- DIVERS (مُتَفَرِّقَاتٌ) ---
    { arabe: "نَصِيحَةٌ", francais: "Conseil" },
    { arabe: "مُشْكِلَةٌ", francais: "Problème" },
    { arabe: "حَلٌّ", francais: "Solution" },
    { arabe: "فُرْصَةٌ", francais: "Opportunité / Chance" },
    { arabe: "سِرٌّ", francais: "Secret" },
    { arabe: "عَادَةٌ", francais: "Habitude" },
    { arabe: "هَدِيَّةٌ", francais: "Cadeau" },
    { arabe: "مُفَاجَأَةٌ", francais: "Surprise" },
    { arabe: "حَقِيقَةٌ", francais: "Vérité / Réalité" },
    { arabe: "خَيَالٌ", francais: "Imagination / Fiction" },
// --- TRAVAIL ET ENTREPRISE (الْعَمَلُ وَالشَّرِكَةُ) ---
    { arabe: "شَرِكَةٌ", francais: "Entreprise / Société" },
    { arabe: "مَشْرُوعٌ", francais: "Projet" },
    { arabe: "اجْتِمَاعٌ", francais: "Réunion" },
    { arabe: "زَمِيلٌ", francais: "Collègue" },
    { arabe: "مُوَظَّفٌ", francais: "Employé" },
    { arabe: "رَاتِبٌ", francais: "Salaire" },
    { arabe: "عَقْدٌ", francais: "Contrat" },
    { arabe: "خِبْرَةٌ", francais: "Expérience" },
    { arabe: "مِهْنَةٌ", francais: "Profession / Métier" },
    { arabe: "بِطَالَةٌ", francais: "Chômage" },
    { arabe: "إِجَازَةٌ", francais: "Congé / Vacances" },
    { arabe: "تَقَاعُدٌ", francais: "Retraite" },
    // --- MESURES ET QUANTITÉS (الْمَقَايِيسُ وَالْكَمِيَّاتُ) ---
    { arabe: "مِيزَانٌ", francais: "Balance" },
    { arabe: "مِسْطَرَةٌ", francais: "Règle" },
    { arabe: "مِقْيَاسُ الْحَرَارَةِ", francais: "Thermomètre" },
    { arabe: "وَزْنٌ", francais: "Poids" },
    { arabe: "طُولٌ", francais: "Longueur / Taille" },
    { arabe: "عَرْضٌ", francais: "Largeur" },
    { arabe: "عُمْقٌ", francais: "Profondeur" },
    { arabe: "مَسَافَةٌ", francais: "Distance" },
    { arabe: "مِسَاحَةٌ", francais: "Surface / Aire" },
    { arabe: "حَجْمٌ", francais: "Volume" },
    { arabe: "ثَقِيلٌ", francais: "Pesant / Lourd" },
    { arabe: "خَفِيفٌ", francais: "Léger" },
    // --- ARTS ET CULTURE (الْفُنُونُ وَالثَّقَافَةُ) ---
    { arabe: "شِعْرٌ", francais: "Poésie" },
    { arabe: "رِوَايَةٌ", francais: "Roman" },
    { arabe: "قِصَّةٌ", francais: "Histoire / Conte" },
    { arabe: "نَحْتٌ", francais: "Sculpture" },
    { arabe: "رَقْصٌ", francais: "Danse" },
    { arabe: "هَنْدَسَةٌ مِعْمَارِيَّةٌ", francais: "Architecture" },
    { arabe: "مَعْرِضٌ", francais: "Exposition" },
    { arabe: "لَوْحَةٌ فَنِّيَّةٌ", francais: "Tableau / Peinture" },
    { arabe: "مَوْهِبَةٌ", francais: "Talent" },
    { arabe: "إِبْدَاعٌ", francais: "Créativité" },
    // --- VERBES DE CHANGEMENT ET DÉVELOPPEMENT (أَفْعَالُ التَّغْيِيرِ) ---
    { arabe: "تَغَيَّرَ", francais: "Changer (soi-même)" },
    { arabe: "غَيَّرَ", francais: "Changer (quelque chose)" },
    { arabe: "تَطَوَّرَ", francais: "Se développer" },
    { arabe: "نَمَا", francais: "Grandir / Croître" },
    { arabe: "تَحَوَّلَ", francais: "Se transformer" },
    { arabe: "نَقَصَ", francais: "Diminuer" },
    { arabe: "زَادَ", francais: "Augmenter" },
    { arabe: "تَحَسَّنَ", francais: "S'améliorer" },
    { arabe: "فَشِلَ", francais: "Échouer" },
    { arabe: "نَجَحَ", francais: "Réussir" },
    // --- MÉDIAS ET COMMUNICATION (الإِعْلَامُ) ---
    { arabe: "خَبَرٌ", francais: "Nouvelle / Information" },
    { arabe: "إِعْلَانٌ", francais: "Publicité / Annonce" },
    { arabe: "قَنَاةٌ", francais: "Chaîne (TV)" },
    { arabe: "بَثٌّ مُبَاشِرٌ", francais: "Direct / Live" },
    { arabe: "مُقَابَلَةٌ", francais: "Entretien / Interview" },
    { arabe: "مَقَالٌ", francais: "Article" },
    { arabe: "مَجَلَّةٌ", francais: "Magazine" },
    { arabe: "جَرِيدَةٌ", francais: "Journal" },
    // --- QUALITÉS DIVERSES (صِفَاتٌ مُتَنَوِّعَةٌ) ---
    { arabe: "مُهِمٌّ", francais: "Important" },
    { arabe: "ضَرُورِيٌّ", francais: "Nécessaire" },
    { arabe: "مُفِيدٌ", francais: "Utile" },
    { arabe: "خَطِيرٌ", francais: "Dangereux" },
    { arabe: "آمِنٌ", francais: "Sûr / En sécurité" },
    { arabe: "مُمِلٌّ", francais: "Ennuyeux" },
    { arabe: "مُمْتِعٌ", francais: "Amusant / Plaisant" },
    { arabe: "غَرِيبٌ", francais: "Étrange / Bizarre" },
    { arabe: "عَادِيٌّ", francais: "Normal / Ordinaire" },
    { arabe: "مِثَالِيٌّ", francais: "Idéal / Parfait" },
// --- ADMINISTRATION ET DOCUMENTS (الإِدَارَةُ وَالْوَثَائِقُ) ---
    { arabe: "تَوْقِيعٌ", francais: "Signature" },
    { arabe: "طَلَبٌ", francais: "Demande / Formulaire" },
    { arabe: "مِلَفٌّ", francais: "Dossier" },
    { arabe: "هُوِيَّةٌ", francais: "Identité" },
    { arabe: "شَهَادَةٌ", francais: "Diplôme / Certificat" },
    { arabe: "خَتْمٌ", francais: "Cachet / Tampon" },
    { arabe: "رَقْمٌ", francais: "Numéro" },
    { arabe: "قَائِمَةٌ", francais: "Liste" },
    { arabe: "وَرَقَةٌ رَسْمِيَّةٌ", francais: "Papier officiel" },
    { arabe: "مَوْعِدٌ نِهَائِيٌّ", francais: "Date limite" },
    // --- POLITESSE ET VIE SOCIALE (الآدَابُ وَالِاجْتِمَاعِيَّاتُ) ---
    { arabe: "مَبْرُوكٌ", francais: "Félicitations" },
    { arabe: "تَهَانِينَا", francais: "Nos félicitations" },
    { arabe: "لِلْأَسَفِ", francais: "Malheureusement" },
    { arabe: "بِالتَّأْكِيدِ", francais: "Certainement / Bien sûr" },
    { arabe: "طَبْعاً", francais: "Évidemment" },
    { arabe: "رُبَّمَا", francais: "Peut-être" },
    { arabe: "مُوَافِقٌ", francais: "D'accord" },
    { arabe: "مَعْذِرَةً", francais: "Excusez-moi" },
    { arabe: "آسِفٌ", francais: "Désolé" },
    { arabe: "تَفَضَّلْ", francais: "Je t'en prie / Tiens" },
    // --- LES CINQ SENS ET ACTIONS (الْحَوَاسُّ الْخَمْسُ) ---
    { arabe: "نَظَرَ", francais: "Regarder" },
    { arabe: "سَمِعَ", francais: "Entendre" },
    { arabe: "شَمَّ", francais: "Sentir (odeur)" },
    { arabe: "ذَاقَ", francais: "Goûter" },
    { arabe: "لَمَسَ", francais: "Toucher" },
    { arabe: "شَعَرَ", francais: "Ressentir" },
    { arabe: "رَأَى", francais: "Voir" },
    { arabe: "أَبْصَرَ", francais: "Apercevoir" },
    { arabe: "تَنَفَّسَ", francais: "Respirer" },
    { arabe: "بَكَى", francais: "Pleurer" },
    // --- LOGIQUE ET ARGUMENTATION (الْمَنْطِقُ) ---
    { arabe: "سَبَبٌ", francais: "Raison / Cause" },
    { arabe: "تِيجَةٌ", francais: "Résultat" },
    { arabe: "مِثَالٌ", francais: "Exemple" },
    { arabe: "دَلِيلٌ", francais: "Preuve / Guide" },
    { arabe: "رَأْيٌ", francais: "Avis / Opinion" },
    { arabe: "فِكْرَةٌ", francais: "Idée" },
    { arabe: "مَوْضُوعٌ", francais: "Sujet" },
    { arabe: "مَعْنًى", francais: "Sens / Signification" },
    { arabe: "هَدَفٌ", francais: "But / Objectif" },
    { arabe: "نِظَامٌ", francais: "Système / Ordre" },
    // --- MATÉRIAUX ET TEXTURES (مَوَادُّ وَمَلْمَسٌ) ---
    { arabe: "نَاعِمٌ", francais: "Doux / Lisse" },
    { arabe: "خَشِنٌ", francais: "Rude / Rugueux" },
    { arabe: "مَبْلُولٌ", francais: "Mouillé" },
    { arabe: "جَافٌّ", francais: "Sec" },
    { arabe: "مُضِيءٌ", francais: "Lumineux" },
    { arabe: "مُظْلِمٌ", francais: "Sombre" },
    { arabe: "وَاسِعٌ", francais: "Large / Spacieux" },
    { arabe: "ضَيِّقٌ", francais: "Étroit" },
    { arabe: "مُمْتَلِئٌ", francais: "Plein" },
    { arabe: "فَارِغٌ", francais: "Vide" },
    // --- ÉVÉNEMENTS DE LA VIE (أَحْدَاثُ الْحَيَاةِ) ---
    { arabe: "وِلَادَةٌ", francais: "Naissance" },
    { arabe: "مَوْتٌ", francais: "Mort" },
    { arabe: "زَوَاجٌ", francais: "Mariage" },
    { arabe: "حَفْلَةٌ", francais: "Fête" },
    { arabe: "عِيدُ مِيلَادٍ", francais: "Anniversaire" },
    { arabe: "اجْتِمَاعٌ عَائِلِيٌّ", francais: "Réunion de famille" },
    { arabe: "ذِكْرَى", francais: "Souvenir / Commémoration" },
    { arabe: "نَجَاحٌ", francais: "Réussite" },
    // --- DERNIERS MOTS INDISPENSABLES (كَلِمَاتٌ خِتَامِيَّةٌ) ---
    { arabe: "جِدّاً", francais: "Très" },
    { arabe: "قَلِيلاً", francais: "Un peu" },
    { arabe: "كَثِيراً", francais: "Beaucoup" },
    { arabe: "بُطْءٌ", francais: "Lenteur" },
    { arabe: "سُرْعَةٌ", francais: "Vitesse" },
    { arabe: "قُوَّةٌ", francais: "Force" },
    { arabe: "ضَوْءٌ", francais: "Lumière" },
    { arabe: "ظِلٌّ", francais: "Ombre" },
    { arabe: "صَوْتٌ", francais: "Bruit / Son" },
    { arabe: "هُدُوءٌ", francais: "Calme / Silence" },
    { arabe: "خَتْمٌ", francais: "Fin / Conclusion" },
     // --- vocabulaire Coranique ---
    { arabe: "ٱللَّه", francais: "Allah (Dieu)" },
    { arabe: "رَبّ", francais: "Seigneur" },
    { arabe: "رَسُول", francais: "Messager" },
    { arabe: "نَبِيّ", francais: "Prophète" },
    { arabe: "كِتَاب", francais: "Livre" },
    { arabe: "قُرْآن", francais: "Lecture / Coran" },
    { arabe: "آيَة", francais: "Signe / Verset" },
    { arabe: "سُورَة", francais: "Sourate (Chapitre)" },
    { arabe: "دِين", francais: "Religion / Jugement" },
    { arabe: "إِيمَان", francais: "Foi" },
    { arabe: "كُفْر", francais: "Mécréance" },
    { arabe: "جَنَّة", francais: "Paradis (Jardin)" },
    { arabe: "نَار", francais: "Feu (Enfer)" },
    { arabe: "يَوْم", francais: "Jour" },
    { arabe: "دُنْيَا", francais: "Monde présent" },
    { arabe: "آخِرَة", francais: "Vie dernière" },
    { arabe: "سَمَاء", francais: "Ciel" },
    { arabe: "أَرْض", francais: "Terre" },
    { arabe: "مَاء", francais: "Eau" },
    { arabe: "نُور", francais: "Lumière" },
    { arabe: "ظُلُمَات", francais: "Ténèbres" },
    { arabe: "حَقّ", francais: "Vérité" },
    { arabe: "بَاطِل", francais: "Faux" },
    { arabe: "خَيْر", francais: "Bien" },
    { arabe: "شَرّ", francais: "Mal" },
    { arabe: "قَلْب", francais: "Cœur" },
    { arabe: "عِلْم", francais: "Science / Savoir" },
    { arabe: "حِكْمَة", francais: "Sagesse" },
    { arabe: "رَحْمَة", francais: "Miséricorde" },
    { arabe: "عَذَاب", francais: "Châtiment" },
    { arabe: "غَفُور", francais: "Pardonneur" },
    { arabe: "رَحِيم", francais: "Très Miséricordieux" },
    { arabe: "عَلِيم", francais: "Omniscient" },
    { arabe: "قَدِير", francais: "Omnipotent" },
    { arabe: "عَزِيز", francais: "Puissant" },
    { arabe: "حَكِيم", francais: "Sage" },
    { arabe: "شَهيد", francais: "Témoin" },
    { arabe: "مَلَك", francais: "Ange" },
    { arabe: "جِنّ", francais: "Djinn" },
    { arabe: "إِنْسَان", francais: "Être humain" },
    { arabe: "نَاس", francais: "Gens" },
    { arabe: "قَوْم", francais: "Peuple" },
    { arabe: "أُمَّة", francais: "Communauté" },
    { arabe: "أَب", francais: "Père" },
    { arabe: "أُمّ", francais: "Mère" },
    { arabe: "ابْن", francais: "Fils" },
    { arabe: "أَخ", francais: "Frère" },
    { arabe: "زَوْج", francais: "Époux / Couple" },
    { arabe: "صَلَاة", francais: "Prière" },
    { arabe: "زَكَاة", francais: "Aumône légale" },
    { arabe: "صَوْم", francais: "Jeûne" },
    { arabe: "حَجّ", francais: "Pèlerinage" },
    { arabe: "دُعَاء", francais: "Invocation" },
    { arabe: "ذِكْر", francais: "Rappel" },
    { arabe: "عِبَادَة", francais: "Adoration" },
    { arabe: "صَبْر", francais: "Patience" },
    { arabe: "شُكْر", francais: "Reconnaissance" },
    { arabe: "تَقْوَى", francais: "Piété" },
    { arabe: "إِحْسَان", francais: "Excellence / Bienfaisance" },
    { arabe: "ظُلْم", francais: "Injustice" },
    { arabe: "فَسَاد", francais: "Corruption" },
    { arabe: "إِثْم", francais: "Péché" },
    { arabe: "ذَنْب", francais: "Faute" },
    { arabe: "تَوْبَة", francais: "Repentir" },
    { arabe: "هُدَى", francais: "Guidée" },
    { arabe: "ضَلَال", francais: "Égarement" },
    { arabe: "صِرَاط", francais: "Chemin" },
    { arabe: "مُسْتَقِيم", francais: "Droit" },
    { arabe: "مُؤْمِن", francais: "Croyant" },
    { arabe: "مُسْلِم", francais: "Soumis (Musulman)" },
    { arabe: "كَافِر", francais: "Mécréant" },
    { arabe: "مُنَافِق", francais: "Hypocrite" },
    { arabe: "مُشْرِك", francais: "Associateur" },
    { arabe: "وَلِيّ", francais: "Allié / Protecteur" },
    { arabe: "نَصِير", francais: "Secoureur" },
    { arabe: "عَهْد", francais: "Pacte" },
    { arabe: "وَعْد", francais: "Promesse" },
    { arabe: "بَيْت", francais: "Maison" },
    { arabe: "مَسْجِد", francais: "Lieu de prosternation" },
    { arabe: "طَعَام", francais: "Nourriture" },
    { arabe: "رِزْق", francais: "Subsistance" },
    { arabe: "حَيَاة", francais: "Vie" },
    { arabe: "مَوْت", francais: "Mort" },
    { arabe: "بَعْث", francais: "Résurrection" },
    { arabe: "حِسَاب", francais: "Compte" },
    { arabe: "مِيزَان", francais: "Balance" },
    { arabe: "أَجْر", francais: "Récompense" },
    { arabe: "فَضْل", francais: "Grâce" },
    { arabe: "شَمْس", francais: "Soleil" },
    { arabe: "قَمَر", francais: "Lune" },
    { arabe: "نَجْم", francais: "Étoile" },
    { arabe: "لَيْل", francais: "Nuit" },
    { arabe: "نَهَار", francais: "Jour (clarté)" },
    { arabe: "بَحْر", francais: "Mer" },
    { arabe: "جَبَل", francais: "Montagne" },
    { arabe: "شَجَرَة", francais: "Arbre" },
    { arabe: "ثَمَرَة", francais: "Fruit" },
    { arabe: "عَدْل", francais: "Justice" },
    { arabe: "قُوَّة", francais: "Force" },
    { arabe: "رُوح", francais: "Esprit / Âme" },
    { arabe: "قَالَ", francais: "Il a dit" },
    { arabe: "كَانَ", francais: "Il était" },
    { arabe: "آمَنَ", francais: "Il a cru" },
    { arabe: "عَمِلَ", francais: "Il a fait / œuvré" },
    { arabe: "جَعَلَ", francais: "Il a fait / rendu" },
    { arabe: "جَاءَ", francais: "Il est venu" },
    { arabe: "شَاءَ", francais: "Il a voulu" },
    { arabe: "خَلَقَ", francais: "Il a créé" },
    { arabe: "أَنْزَلَ", francais: "Il a fait descendre" },
    { arabe: "كَذَّبَ", francais: "Il a traité de mensonge" },
    { arabe: "دَعَا", francais: "Il a invoqué / appelé" },
    { arabe: "هَدَى", francais: "Il a guidé" },
    { arabe: "أَرَادَ", francais: "Il a voulu / désiré" },
    { arabe: "اتَّبَعَ", francais: "Il a suivi" },
    { arabe: "أَتَى", francais: "Il est venu / a apporté" },
    { arabe: "بَعَثَ", francais: "Il a ressuscité / envoyé" },
    { arabe: "تَوَلَّى", francais: "Il s'est détourné" },
    { arabe: "خَافَ", francais: "Il a eu peur" },
    { arabe: "رَأَى", francais: "Il a vu" },
    { arabe: "سَبَّحَ", francais: "Il a glorifié" },
    { arabe: "عَبْد", francais: "Serviteur / Esclave" },
    { arabe: "أَوْلِيَاء", francais: "Alliés / Protecteurs" },
    { arabe: "مَلَائِكَة", francais: "Anges" },
    { arabe: "شَيْطَان", francais: "Satan" },
    { arabe: "آبَاء", francais: "Pères / Ancêtres" },
    { arabe: "بَنِي", francais: "Fils de / Enfants de" },
    { arabe: "ذُرِّيَّة", francais: "Descendance" },
    { arabe: "أَهْل", francais: "Gens / Famille" },
    { arabe: "نِسَاء", francais: "Femmes" },
    { arabe: "رِجَال", francais: "Hommes" },
    { arabe: "أَعْدَاء", francais: "Ennemis" },
    { arabe: "مُجْرِم", francais: "Criminel" },
    { arabe: "صَالِح", francais: "Vertueux / Bon" },
    { arabe: "غَافِل", francais: "Inattentif" },
    { arabe: "بَيِّنَة", francais: "Preuve évidente" },
    { arabe: "فُرْقَان", francais: "Discernement" },
    { arabe: "بُشْرَى", francais: "Bonne nouvelle" },
    { arabe: "نَذِير", francais: "Avertisseur" },
    { arabe: "شَفَاعَة", francais: "Intercession" },
    { arabe: "قِيَامَة", francais: "Résurrection" },
    { arabe: "سَاعَة", francais: "L'Heure (Jugement)" },
    { arabe: "صُحُف", francais: "Feuillets / Livres" },
    { arabe: "فَوْز", francais: "Succès / Triomphe" },
    { arabe: "خُسْرَان", francais: "Perte / Échec" },
    { arabe: "لَعْنَة", francais: "Malédiction" },
    { arabe: "مَغْفِرَة", francais: "Pardon" },
    { arabe: "عَهْد", francais: "Pacte / Engagement" },
    { arabe: "رِيح", francais: "Vent" },
    { arabe: "سَحَاب", francais: "Nuages" },
    { arabe: "مَطَر", francais: "Pluie" },
    { arabe: "أَنْهَار", francais: "Rivières" },
    { arabe: "بُحُور", francais: "Mers" },
    { arabe: "كَوَاكِب", francais: "Astres / Planètes" },
    { arabe: "ظِلّ", francais: "Ombre" },
    { arabe: "حِجَارة", francais: "Pierres" },
    { arabe: "طِين", francais: "Argile / Boue" },
    { arabe: "تُرَاب", francais: "Poussière / Terre" },
    { arabe: "نَبَات", francais: "Plantes" },
    { arabe: "حَبّ", francais: "Graine" },
    { arabe: "قَلِيل", francais: "Peu / Faible quantité" },
    { arabe: "كَثِير", francais: "Beaucoup / Nombreux" },
    { arabe: "شَدِيد", francais: "Intense / Dur" },
    { arabe: "عَظِيم", francais: "Immense / Grand" },
    { arabe: "عَلِيّ", francais: "Élevé" },
    { arabe: "قَرِيب", francais: "Proche" },
    { arabe: "بَعِيد", francais: "Lointain" },
    { arabe: "مُبِين", francais: "Clair / Explicite" },
    { arabe: "كَرِيم", francais: "Noble / Généreux" },
    { arabe: "عَزِيز", francais: "Puissant / Cher" },
    { arabe: "لَطِيف", francais: "Doux / Subtil" },
    { arabe: "أَنْ", francais: "Que" },
    { arabe: "إِذَا", francais: "Quand / Lorsque" },
    { arabe: "إِنْ", francais: "Si" },
    { arabe: "لَوْ", francais: "Si (conditionnel)" },
    { arabe: "لَمْ", francais: "Ne... pas (passé)" },
    { arabe: "لَنْ", francais: "Ne... jamais (futur)" },
    { arabe: "أَيُّ", francais: "Lequel / Quel" },
    { arabe: "كَيْفَ", francais: "Comment" },
    { arabe: "أَيْنَ", francais: "Où" },
    { arabe: "مَتَى", francais: "Quand" },
    { arabe: "بَلْ", francais: "Mais / Plutôt" },
    { arabe: "ثُمَّ", francais: "Ensuite" },
    { arabe: "قَبْل", francais: "Avant" },
    { arabe: "بَعْد", francais: "Après" },
    { arabe: "تَحْت", francais: "Sous" },
    { arabe: "فَوْق", francais: "Au-dessus" },
    { arabe: "بَيْن", francais: "Entre" },
    { arabe: "أَمَام", francais: "Devant" },
    { arabe: "خَلْف", francais: "Derrière" },
    { arabe: "حَوْل", francais: "Autour" },
    { arabe: "أَيَّام", francais: "Jours" },
    { arabe: "شُهُور", francais: "Mois" },
    { arabe: "سِنِين", francais: "Années" },
    { arabe: "قِسْط", francais: "Équité / Justice" },
    { arabe: "مِيثَاق", francais: "Alliance solennelle" },
    { arabe: "أَمَانَة", francais: "Dépôt de confiance" },
    { arabe: "بَيْع", francais: "Vente / Commerce" },
    { arabe: "تِجَارَة", francais: "Négoce" },
    { arabe: "رِبَا", francais: "Usure / Intérêt" },
    { arabe: "دَيْن", francais: "Dette" },
    { arabe: "شَهَادَة", francais: "Témoignage" },
    { arabe: "مِيرَاث", francais: "Héritage" },
    { arabe: "نِكاح", francais: "Mariage" },
    { arabe: "طَلَاق", francais: "Divorce" },
    { arabe: "حُدُود", francais: "Limites (lois)" },
    { arabe: "صَدْر", francais: "Poitrine (siège du cœur)" },
    { arabe: "فُؤَاد", francais: "Cœur profond / Introspection" },
    { arabe: "لُبّ", francais: "Essence / Intelligence" },
    { arabe: "نَفْس", francais: "Âme / Soi-même" },
    { arabe: "هَوَى", francais: "Passion / Désir bas" },
    { arabe: "غَيْظ", francais: "Rage / Colère" },
    { arabe: "حُبّ", francais: "Amour" },
    { arabe: "بُغْض", francais: "Haine" },
    { arabe: "فَرَح", francais: "Joie" },
    { arabe: "حُزْن", francais: "Tristesse" },
    { arabe: "خَوْف", francais: "Crainte" },
    { arabe: "رَجَاء", francais: "Espoir" },
    { arabe: "غَيْب", francais: "L'Invisible / L'Inconnu" },
    { arabe: "وَحْي", francais: "Révélation" },
    { arabe: "سُلْطَان", francais: "Preuve d'autorité" },
    { arabe: "بَرَكَة", francais: "Bénédiction" },
    { arabe: "سَكِينَة", francais: "Sérénité" },
    { arabe: "طُمَأْنِينَة", francais: "Quiétude" },
    { arabe: "فِتْنَة", francais: "Épreuve / Tentation" },
    { arabe: "بَلَاء", francais: "Test / Examen" },
    { arabe: "وَاقِعَة", francais: "L'Événement (inéluctable)" },
    { arabe: "قَارِعَة", francais: "Le Fracas" },
    { arabe: "رَاجِفَة", francais: "Le Secousse" },
    { arabe: "زَلْزَلَة", francais: "Tremblement de terre" },
    { arabe: "كِتَاب مَرْقُوم", francais: "Livre scellé / écrit" },
    { arabe: "عِلِّيِّين", francais: "Lieu des plus hauts" },
    { arabe: "سِجِّين", francais: "Lieu des bas-fonds" },
    { arabe: "زَقُّوم", francais: "Arbre de l'enfer" },
    { arabe: "سَلْسَبِيل", francais: "Source du paradis" },
    { arabe: "لِبَاس", francais: "Vêtement" },
    { arabe: "حَرِير", francais: "Soie" },
    { arabe: "ذَهَب", francais: "Or" },
    { arabe: "فِضَّة", francais: "Argent" },
    { arabe: "لُؤْلُؤ", francais: "Perle" },
    { arabe: "كَأْس", francais: "Coupe / Verre" },
    { arabe: "مَائِدَة", francais: "Table servie" },
    { arabe: "مِصْبَاح", francais: "Lampe" },
    { arabe: "سِرَاج", francais: "Flambeau" },
    { arabe: "حَبْل", francais: "Corde" },
    { arabe: "سَفِينَة", francais: "Bateau" },
    { arabe: "فُلْك", francais: "Arche / Navire" },
    { "arabe": "يَسْتَعْتِبُونَ", "francais": "Ils cherchent à plaire / se racheter" },
  { "arabe": "يُبْدِئُ", "francais": "Il commence / crée une première fois" },
  { "arabe": "يُعِيدُ", "francais": "Il répète / ressuscite" },
  { "arabe": "يَنْسَخُ", "francais": "Il abroge / efface" },
  { "arabe": "يَسْتَفِزُّ", "francais": "Il excite / incite" },
  { "arabe": "يَحْشُرُ", "francais": "Il rassemble" },
  { "arabe": "يَقْذِفُ", "francais": "Il lance / projette" },
  { "arabe": "يَتَخَطَّفُ", "francais": "Il enlève / ravisse" },
  { "arabe": "يَسْتَنْبِطُ", "francais": "Il déduit / tire au clair" },
  { "arabe": "يُضَاعِفُ", "francais": "Il multiplie / double" },
  { "arabe": "يَسْتَخْلِفُ", "francais": "Il donne la succession" },
  { "arabe": "يَتَمَتَّعُونَ", "francais": "Ils jouissent (des biens)" },
  { "arabe": "يَسْتَطِيعُونَ", "francais": "Ils peuvent / sont capables" },
  { "arabe": "يَمْتَرُونَ", "francais": "Ils doutent / discutent" },
  { "arabe": "يَسْتَفْتُونَ", "francais": "Ils demandent un avis" },
  { "arabe": "مُبْصِرَة", "francais": "Visible / Claire" },
  { "arabe": "مُسْتَنِير", "francais": "Lumineux" },
  { "arabe": "مُطَهَّرَة", "francais": "Purifiée" },
  { "arabe": "مُكَرَّمَة", "francais": "Honorée" },
  { "arabe": "مَرْفُوعَة", "francais": "Élevée" },
  { "arabe": "مَسْطُور", "francais": "Inscrit en lignes" },
  { "arabe": "مَنْشُور", "francais": "Déployé / Étendu" },
  { "arabe": "مَعْمُور", "francais": "Fréquenté / Peuplé" },
  { "arabe": "مَسْجُور", "francais": "Enflammé / Bouillonnant" },
  { "arabe": "مَنْضُود", "francais": "Entassé / Aligné" },
  { "arabe": "مَسْكُوب", "francais": "Répandu / Coulant" },
  { "arabe": "مَوْضُونَة", "francais": "Tissée d'or" },
  { "arabe": "مَخْضُود", "francais": "Sans épines" },
  { "arabe": "مَنْضُود", "francais": "Chargé de fruits" },
  { "arabe": "مَمْدُود", "francais": "Étendu / Prolongé" },
  { "arabe": "مُسْتَطِير", "francais": "Éclatant / Volant" },
  { "arabe": "مُحْتَضَر", "francais": "Fréquenté / Présent" },
  { "arabe": "مُقْتَدِر", "francais": "Puissant / Capable" },
  { "arabe": "مُنْهَمِر", "francais": "Qui coule en abondance" },
  { "arabe": "مُنْدَسِر", "francais": "Effacé / Détruit" },
  { "arabe": "مُسْتَمِرّ", "francais": "Persistant" },
  { "arabe": "مُنْقَلَب", "francais": "Lieu de retour" },
  { "arabe": "مُزْدَجَر", "francais": "Avertissement" },
  { "arabe": "مُسْتَقَرّ", "francais": "Établissement" },
  { "arabe": "مُسْتَوْدَع", "francais": "Lieu de dépôt" },
  { "arabe": "سُقِطَ", "francais": "Il est tombé / a regretté" },
  { "arabe": "نُسِخَ", "francais": "Il a été abrogé" },
  { "arabe": "كُتِبَ", "francais": "Il a été prescrit" },
  { "arabe": "قُتِلَ", "francais": "Il a été tué" },
  { "arabe": "نُفِخَ", "francais": "Il a été soufflé" },
  { "arabe": "زُلْزِلَتْ", "francais": "Elle a tremblé" },
  { "arabe": "حُشِرَتْ", "francais": "Elle a été rassemblée" },
  { "arabe": "كُوِّرَتْ", "francais": "Elle a été obscurcie" },
  { "arabe": "سُجِّرَتْ", "francais": "Elle a été bouillonnée" },
  { "arabe": "عُطِّلَتْ", "francais": "Elle a été abandonnée" },
  { "arabe": "نُشِرَتْ", "francais": "Elle a été déployée" },
  { "arabe": "كُشِطَتْ", "francais": "Elle a été arrachée" },
  { "arabe": "أُزْلِفَتْ", "francais": "Elle a été rapprochée" },
  { "arabe": "فُطِرَتْ", "francais": "Elle a été fendue" },
  { "arabe": "بُعْثِرَتْ", "francais": "Elle a été bouleversée" },
  { "arabe": "سُوِّيَتْ", "francais": "Elle a été égalisée" },
  { "arabe": "خُسِفَ", "francais": "Il a été éclipsé / englouti" },
  { "arabe": "قُصِدَ", "francais": "Il a été visé" },
  { "arabe": "نُودِيَ", "francais": "Il a été appelé" },
  { "arabe": "أُجِّلَتْ", "francais": "Elle a été fixée (délai)" },
    { "arabe": "شَرَاب", "francais": "Boisson" },
  { "arabe": "حَمِيم", "francais": "Eau bouillante" },
  { "arabe": "غَسَّاق", "francais": "Pus / Liquide fétide" },
  { "arabe": "جَزَاء", "francais": "Récompense" },
  { "arabe": "وِفَاق", "francais": "Approprié" },
  { "arabe": "حِسَاب", "francais": "Compte" },
  { "arabe": "كَذَّاب", "francais": "Menteur" },
  { "arabe": "إِحْصَاء", "francais": "Dénombrement" },
  { "arabe": "مَفَاز", "francais": "Lieu de succès" },
  { "arabe": "حَدَائِق", "francais": "Vergers" },
  { "arabe": "أَعْنَاب", "francais": "Vignes" },
  { "arabe": "كَوَاعِب", "francais": "Belles de même âge" },
  { "arabe": "أَتْرَاب", "francais": "Compagnes d'âge égal" },
  { "arabe": "كَأْس", "francais": "Coupe" },
  { "arabe": "دِهَاق", "francais": "Pleine / Débordante" },
  { "arabe": "لَغْو", "francais": "Parole vaine" },
  { "arabe": "عَطَاء", "francais": "Don" },
  { "arabe": "سَمَوَات", "francais": "Cieux" },
  { "arabe": "أَرْض", "francais": "Terre" },
  { "arabe": "رُوح", "francais": "Esprit" },
  { "arabe": "صَفّ", "francais": "Rang" },
  { "arabe": "صَوَاب", "francais": "Vérité / Justesse" },
  { "arabe": "مَآب", "francais": "Retour" },
  { "arabe": "تُرَاب", "francais": "Poussière" },
  { "arabe": "نَاضِرَة", "francais": "Éclatante" },
  { "arabe": "بَاسِرَة", "francais": "Assombrie" },
  { "arabe": "فَاقِرَة", "francais": "Calamité" },
  { "arabe": "تَرَاقِي", "francais": "Clavicules" },
  { "arabe": "رَاق", "francais": "Exorciste" },
  { "arabe": "فِرَاق", "francais": "Séparation" },
  { "arabe": "سَاق", "francais": "Jambe" },
  { "arabe": "مَسَاق", "francais": "Cheminement" },
  { "arabe": "سُدَى", "francais": "À l'abandon" },
  { "arabe": "مَنِيّ", "francais": "Sperme" },
  { "arabe": "يُمْنَى", "francais": "Éjaculé" },
  { "arabe": "نُطْفَة", "francais": "Goutte" },
  { "arabe": "سَوَّى", "francais": "Harmonisé" },
  { "arabe": "ذَكَر", "francais": "Mâle" },
  { "arabe": "أُنْثَى", "francais": "Femelle" },
  { "arabe": "مَوْتَى", "francais": "Morts" },
    // --- FAMILLE DE LA CRÉATION ET DU POUVOIR ---
    { arabe: "بَارِئ", francais: "Le Créateur (Qui donne forme)" },
    { arabe: "مُصَوِّر", francais: "Celui qui façonne" },
    { arabe: "قَهَّار", francais: "Le Dominateur Suprême" },
    { arabe: "وَهَّاب", francais: "Le Donateur généreux" },
    { arabe: "فَتَّاح", francais: "Celui qui accorde la victoire / Ouvre" },
    { arabe: "رَزَّاق", francais: "Le Grand Pourvoyeur" },
    // --- TERMES DE L'HISTOIRE DES PROPHÈTES ---
    { arabe: "أَسَاطِير", francais: "Légendes / Contes" },
    { arabe: "قَصَص", francais: "Récit / Histoire" },
    { arabe: "نَبَأ", francais: "Nouvelle / Information importante" },
    { arabe: "سُلْطَان", francais: "Preuve d'autorité" },
    { arabe: "بُرْهَان", francais: "Preuve irréfutable" },
    { arabe: "تَوْرَاة", francais: "Thora" },
    { arabe: "إِنْجِيل", francais: "Évangile" },
    { arabe: "زَبُور", francais: "Psaumes" },
    // --- LE MONDE VÉGÉTAL ET ANIMAL ---
    { arabe: "نَخْل", francais: "Palmiers" },
    { arabe: "أَعْنَاب", francais: "Vignes" },
    { arabe: "زَيْتُون", francais: "Olives" },
    { arabe: "رُمَّان", francais: "Grenades (fruits)" },
    { arabe: "أَنْعَام", francais: "Bestiaux" },
    { arabe: "خَيْل", francais: "Chevaux" },
    { arabe: "بِغَال", francais: "Mulets" },
    { arabe: "حَمِير", francais: "Ânes" },
    { arabe: "نَحْل", francais: "Abeille" },
    { arabe: "نَمْل", francais: "Fourmi" },
    { arabe: "عَنْكَبُوت", francais: "Araignée" },
    { arabe: "ذُبَاب", francais: "Mouche" },
    // --- ÉTATS PHYSIQUES ET SANTÉ ---
    { arabe: "شِفَاء", francais: "Guérison" },
    { arabe: "مَرَض", francais: "Maladie" },
    { arabe: "عَمِيَ", francais: "Aveugle" },
    { arabe: "بُكْم", francais: "Muet" },
    { arabe: "صُمّ", francais: "Sourd" },
    { arabe: "قُوَّة", francais: "Force" },
    { arabe: "ضَعْف", francais: "Faiblesse" },
    { arabe: "كِبَر", francais: "Vieillesse" },
    // --- ÉLÉMENTS DU COSMOS ---
    { arabe: "مَشَارِق", francais: "Les Orients" },
    { arabe: "مَغَارِب", francais: "Les Occidents" },
    { arabe: "فَلَك", francais: "Orbite" },
    { arabe: "بُرُوج", francais: "Constellations" },
    { arabe: "طَارِق", francais: "Astre nocturne" },
    { arabe: "ثَاقِب", francais: "Étincelant" },
    // --- COMPORTEMENTS HUMAINS ---
    { arabe: "بُخْل", francais: "Avarice" },
    { arabe: "إِسْرَاف", francais: "Gaspillage" },
    { arabe: "تَبْذِير", francais: "Prodigalité" },
    { arabe: "كِبْر", francais: "Orgueil" },
    { arabe: "تَوَاضُع", francais: "Humilité" },
    { arabe: "صِدْق", francais: "Véracité" },
    { arabe: "كَذِب", francais: "Mensonge" },
    { arabe: "خِيَانَة", francais: "Trahison" },
  { "arabe": "ٱللَّه", "francais": "Allah (Dieu)" },
  { "arabe": "رَبّ", "francais": "Seigneur" },
  { "arabe": "رَسُول", "francais": "Messager" },
  { "arabe": "نَبِيّ", "francais": "Prophète" },
  { "arabe": "كِتَاب", "francais": "Livre" },
  { "arabe": "قُرْآن", "francais": "Coran" },
  { "arabe": "آيَة", "francais": "Signe / Verset" },
  { "arabe": "سُورَة", "francais": "Sourate" },
  { "arabe": "إِيمَان", "francais": "Foi" },
  { "arabe": "إِحْسَان", "francais": "Excellence" },
  { "arabe": "تَوْحِيد", "francais": "Unicité" },
  { "arabe": "صَلَاة", "francais": "Prière" },
  { "arabe": "زَكَاة", "francais": "Aumône" },
  { "arabe": "صَوْم", "francais": "Jeûne" },
  { "arabe": "حَجّ", "francais": "Pèlerinage" },
  { "arabe": "جَنَّة", "francais": "Paradis" },
  { "arabe": "نَار", "francais": "Enfer" },
  { "arabe": "مَلَك", "francais": "Ange" },
  { "arabe": "دُعَاء", "francais": "Invocation" },
  { "arabe": "ذِكْر", "francais": "Rappel" },
  { "arabe": "حَلَال", "francais": "Licite" },
  { "arabe": "حَرَام", "francais": "Illicite" },
  { "arabe": "قِبْلَة", "francais": "Direction" },
  { "arabe": "وُضُوء", "francais": "Ablutions" },
  { "arabe": "نِيَّة", "francais": "Intention" },
  { "arabe": "تَوْبَة", "francais": "Repentir" },
  { "arabe": "صَبْر", "francais": "Patience" },
  { "arabe": "شُكْر", "francais": "Gratitude" },
  { "arabe": "عِلْم", "francais": "Science" },
  { "arabe": "حِكْمَة", "francais": "Sagesse" },
  { "arabe": "رَحْمَة", "francais": "Miséricorde" },
  { "arabe": "عَذَاب", "francais": "Châtiment" },
  { "arabe": "حَقّ", "francais": "Vérité" },
  { "arabe": "بَاطِل", "francais": "Faux" },
  { "arabe": "دُنْيَا", "francais": "Bas-monde" },
  { "arabe": "آخِرَة", "francais": "Au-delà" },
  { "arabe": "قَلْب", "francais": "Cœur" },
  { "arabe": "نَفْس", "francais": "Âme" },
  { "arabe": "رُوح", "francais": "Esprit" },
  { "arabe": "غَيْب", "francais": "L'invisible" },
  { "arabe": "مَسْجِد", "francais": "Mosquée" },
  { "arabe": "مِنْبَر", "francais": "Chaire" },
  { "arabe": "خُطْبَة", "francais": "Sermon" },
  { "arabe": "رَمَضَان", "francais": "Ramadan" },
  { "arabe": "عِيد", "francais": "Fête" },
  { "arabe": "سُنَّة", "francais": "Tradition" },
  { "arabe": "حَدِيث", "francais": "Parole" },
  { "arabe": "تَفْسِير", "francais": "Exégèse" },
  { "arabe": "فِقْه", "francais": "Droit" },
  { "arabe": "فَتْوَى", "francais": "Avis" },
  { "arabe": "شَهَادَة", "francais": "Témoignage" },
  { "arabe": "بَرَكَة", "francais": "Bénédiction" },
  { "arabe": "سَكِينَة", "francais": "Sérénité" },
  { "arabe": "فِتْنَة", "francais": "Épreuve" },
  { "arabe": "بَلَاء", "francais": "Test" },
  { "arabe": "إِثْم", "francais": "Péché" },
  { "arabe": "ذَنْب", "francais": "Faute" },
  { "arabe": "أَمَانَة", "francais": "Confiance" },
  { "arabe": "حَيَاء", "francais": "Pudeur" },
  { "arabe": "تَقْوَى", "francais": "Piété" },
  { "arabe": "بِرّ", "francais": "Bonté" },
  { "arabe": "عَدْل", "francais": "Justice" },
  { "arabe": "ظُلْم", "francais": "Injustice" },
  { "arabe": "مِيزَان", "francais": "Balance" },
  { "arabe": "حِسَاب", "francais": "Compte" },
  { "arabe": "قِيَامَة", "francais": "Résurrection" },
  { "arabe": "سَاعَة", "francais": "L'Heure" },
  { "arabe": "عَرْش", "francais": "Trône" },
  { "arabe": "كُرْسِيّ", "francais": "Piédestal" },
  { "arabe": "مَلِك", "francais": "Souverain" },
  { "arabe": "قُدُّوس", "francais": "Saint" },
  { "arabe": "سَلَام", "francais": "Paix" },
  { "arabe": "أَحَد", "francais": "Unique" },
  { "arabe": "صَمَد", "francais": "Absolu" },
  { "arabe": "غَفُور", "francais": "Pardonneur" },
  { "arabe": "رَحِيم", "francais": "Très Miséricordieux" },
  { "arabe": "عَلِيم", "francais": "Omniscient" },
  { "arabe": "قَدِير", "francais": "Omnipotent" },
  { "arabe": "عَزِيز", "francais": "Puissant" },
  { "arabe": "حَكِيم", "francais": "Sage" },
  { "arabe": "خَالِق", "francais": "Créateur" },
  { "arabe": "بَارِئ", "francais": "Novateur" },
  { "arabe": "مُصَوِّر", "francais": "Façonneur" },
  { "arabe": "رَزَّاق", "francais": "Pourvoyeur" },
  { "arabe": "وَهَّاب", "francais": "Donateur" },
  { "arabe": "فَتَّاح", "francais": "Celui qui ouvre" },
  { "arabe": "قَهَّار", "francais": "Dominateur" },
  { "arabe": "مُبِين", "francais": "Évident" },
  { "arabe": "نُور", "francais": "Lumière" },
  { "arabe": "ظُلُمَات", "francais": "Ténèbres" },
  { "arabe": "هُدَى", "francais": "Guidée" },
  { "arabe": "ضَلَال", "francais": "Égarement" },
  { "arabe": "صِرَاط", "francais": "Chemin" },
  { "arabe": "مُسْتَقِيم", "francais": "Droit" },
  { "arabe": "بَيِّنَة", "francais": "Preuve" },
  { "arabe": "فُرْقَان", "francais": "Discernement" },
  { "arabe": "بُشْرَى", "francais": "Bonne nouvelle" },
  { "arabe": "نَذِير", "francais": "Avertisseur" },
  { "arabe": "شَفَاعَة", "francais": "Intercession" },
  { "arabe": "بَرْزَخ", "francais": "Intervalle" },
    //--- Les piliers et conditions (Arkan & Shurut)---
  { "arabe": "أَرْكَان", "francais": "Piliers (fondements)" },
  { "arabe": "شُرُوط", "francais": "Conditions (prérequis)" },
  { "arabe": "أَهْلِيَّة", "francais": "Capacité juridique" },
  { "arabe": "بُلُوغ", "francais": "Puberté (maturité)" },
  { "arabe": "عَقْل", "francais": "Raison / Santé mentale" },
  { "arabe": "قَصْد", "francais": "Détermination / Intention" },
  { "arabe": "إِجْمَاع", "francais": "Consensus des savants" },
  { "arabe": "قِيَاس", "francais": "Raisonnement par analogie" },
  { "arabe": "مَصْلَحَة", "francais": "Intérêt général" },
  { "arabe": "عُرْف", "francais": "Coutume / Usage" },
  { "arabe": "تَقْلِيد", "francais": "Suivi d'une école juridique" },
  { "arabe": "إِجْتِهَاد", "francais": "Effort d'interprétation" },
    //--- Le Droit de la Famille (Munakahat)---
   { "arabe": "وَلِيّ", "francais": "Tuteur légal" },
  { "arabe": "صَدَاق", "francais": "Dot (don nuptial)" },
  { "arabe": "مَهْر", "francais": "Dot" },
  { "arabe": "عَقْد", "francais": "Contrat" },
  { "arabe": "شُهُود", "francais": "Témoins" },
  { "arabe": "خُلْع", "francais": "Divorce demandé par l'épouse" },
  { "arabe": "عِدَّة", "francais": "Délai de viduité" },
  { "arabe": "نَفَقَة", "francais": "Pension alimentaire / Entretien" },
  { "arabe": "حَضَانَة", "francais": "Garde des enfants" },
  { "arabe": "رَضَاعَة", "francais": "Allaitement" },
  { "arabe": "نَسَب", "francais": "Filiation" },
  { "arabe": "مَحْرَم", "francais": "Parent non-mariable" },
    //--- Transactions et Commerce (Mu'amalat)---
   { "arabe": "قَرْض", "francais": "Prêt" },
  { "arabe": "رَهْن", "francais": "Gage / Hypothèque" },
  { "arabe": "هِبَة", "francais": "Don / Cadeau" },
  { "arabe": "وَقْف", "francais": "Fondation pieuse (bien inaliénable)" },
  { "arabe": "شَرِكَة", "francais": "Société / Partenariat" },
  { "arabe": "ضَمَان", "francais": "Garantie" },
  { "arabe": "وَكَالَة", "francais": "Procuration / Mandat" },
  { "arabe": "أَمَانَة", "francais": "Dépôt de confiance" },
  { "arabe": "غَرَر", "francais": "Incertitude excessive (interdite)" },
  { "arabe": "مَيْسِر", "francais": "Jeux de hasard" },
  { "arabe": "ثَمَن", "francais": "Prix" },
  { "arabe": "سِلْعَة", "francais": "Marchandise" },
    //--- Crimes et Peines (Uqubat)---
   { "arabe": "جِنَايَة", "francais": "Crime / Délit" },
  { "arabe": "قِصَاص", "francais": "Loi du talion (réparation)" },
  { "arabe": "دِيَة", "francais": "Prix du sang (compensation)" },
  { "arabe": "حَدّ", "francais": "Peine prescrite (limite)" },
  { "arabe": "تَعْزِير", "francais": "Peine discrétionnaire (jugée par le juge)" },
  { "arabe": "سِرْقَة", "francais": "Vol" },
  { "arabe": "قَذْف", "francais": "Calomnie" },
  { "arabe": "بَيِّنَة", "francais": "Preuve matérielle" },
  { "arabe": "يَمِين", "francais": "Serment" },
  { "arabe": "إِقْرَار", "francais": "Aveu" },
    //---États de l'acte juridique (Ahkam)---
   { "arabe": "صَحِيح", "francais": "Valide" },
  { "arabe": "بَاطِل", "francais": "Nul / Invalide" },
  { "arabe": "فَاسِد", "francais": "Vicié" },
  { "arabe": "مُبَاح", "francais": "Autorisé (neutre)" },
  { "arabe": "مَحْظُور", "francais": "Interdit" },
  { "arabe": "عَزِيمَة", "francais": "Règle générale" },
  { "arabe": "رُخْصَة", "francais": "Dispense / Dérogation" },
     //---Le Temps et les Cycles---
  { "arabe": "دَهْر", "francais": "L'éternité / Le temps long" },
  { "arabe": "عَصْر", "francais": "Le temps qui passe / L'après-midi" },
  { "arabe": "فَجْر", "francais": "L'aube" },
  { "arabe": "شَفَق", "francais": "Crépuscule" },
  { "arabe": "ضُحَى", "francais": "Matinée (clarté du jour)" },
  { "arabe": "سَرْمَد", "francais": "Continuité éternelle" },
  { "arabe": "أَبَد", "francais": "À jamais" },
  { "arabe": "حِين", "francais": "Un instant / Un moment" },
  { "arabe": "آن", "francais": "Maintenant" },
  { "arabe": "أَمْس", "francais": "Hier" },
     //---Le Ciel et la Création---
   { "arabe": "فَلَق", "francais": "L'aube naissante" },
  { "arabe": "غَاسِق", "francais": "Obscurité profonde" },
  { "arabe": "وَقَب", "francais": "S'étendre (en parlant de la nuit)" },
  { "arabe": "مَشْرِق", "francais": "Levant (Orient)" },
  { "arabe": "مَغْرِب", "francais": "Couchant (Occident)" },
  { "arabe": "أُفُق", "francais": "Horizon" },
  { "arabe": "كَوَاكِب", "francais": "Astres / Planètes" },
  { "arabe": "بُرُوج", "francais": "Constellations / Tours" },
  { "arabe": "سِرَاج", "francais": "Lampe (souvent le Soleil)" },
  { "arabe": "شِهَاب", "francais": "Météore / Étoile filante" },
   //---Les Émotions et Qualités du Cœur---
   { "arabe": "رِضْوَان", "francais": "Agrément / Satisfaction" },
  { "arabe": "مَوَدَّة", "francais": "Affection / Amour tendre" },
  { "arabe": "أُنْس", "francais": "Intimité / Convivialité" },
  { "arabe": "خُشُوع", "francais": "Humilité / Recueillement" },
  { "arabe": "إِخْلَاص", "francais": "Sincérité pure" },
  { "arabe": "يَقِين", "francais": "Certitude" },
  { "arabe": "طُمَأْنِينَة", "francais": "Quiétude" },
  { "arabe": "بُشْرَى", "francais": "Annonce joyeuse" },
  { "arabe": "غَيْظ", "francais": "Colère contenue" },
  { "arabe": "حَسْرَة", "francais": "Regret / Remords" },
    //---La Nature et la Terre---
   { "arabe": "وادي", "francais": "Vallée" },
  { "arabe": "بَحْر", "francais": "Mer" },
  { "arabe": "يَمّ", "francais": "Flots / Étendue d'eau" },
  { "arabe": "سُبُل", "francais": "Sentiers / Voies" },
  { "arabe": "رَوَاسِي", "francais": "Montagnes ancrées" },
  { "arabe": "نَبَات", "francais": "Végétation" },
  { "arabe": "حَصَاد", "francais": "Moisson" },
  { "arabe": "زَرْع", "francais": "Culture / Semence" },
  { "arabe": "ثِمَار", "francais": "Fruits" },
  { "arabe": "طِين", "francais": "Argile" },
   //---Actions et Verbes de Vie--- 
   { "arabe": "تَفَكُّر", "francais": "Méditation / Réflexion" },
  { "arabe": "تَدَبُّر", "francais": "Analyse profonde" },
  { "arabe": "سَعْي", "francais": "Effort / Marche" },
  { "arabe": "هِجْرَة", "francais": "Émigration" },
  { "arabe": "جِهَاد", "francais": "Lutte / Effort sur soi" },
  { "arabe": "قِرَاءَة", "francais": "Lecture" },
  { "arabe": "تَرْتِيل", "francais": "Chant psalmodié" },
  { "arabe": "إِنْفَاق", "francais": "Dépense (dans le bien)" },
  { "arabe": "إِطْعَام", "francais": "Nourrir" },
  { "arabe": "إِيتاء", "francais": "Donner / Octroyer" },
   //---Adjectifs et Qualificatifs--- 
   { "arabe": "كَرِيم", "francais": "Généreux / Noble" },
  { "arabe": "بَخِيل", "francais": "Avare" },
  { "arabe": "شَدِيد", "francais": "Intense / Dur" },
  { "arabe": "لَيِّن", "francais": "Souple / Doux" },
  { "arabe": "غَلِيظ", "francais": "Rude / Grossier" },
  { "arabe": "طَيِّب", "francais": "Bon / Pur" },
  { "arabe": "خَبِيث", "francais": "Mauvais / Impur" },
  { "arabe": "قَوِيّ", "francais": "Fort" },
  { "arabe": "ضَعِيف", "francais": "Faible" },
  { "arabe": "كَثِير", "francais": "Nombreux / Beaucoup" },
  { "arabe": "قَلِيل", "francais": "Peu / Rare" },
  { "arabe": "عَرِيض", "francais": "Large" },
  { "arabe": "ضَيِّق", "francais": "Étroit" },
  { "arabe": "ثَقِيل", "francais": "Pesant" },
  { "arabe": "خَفِيف", "francais": "Léger" },
  { "arabe": "مُبَارَك", "francais": "Béni" },
  { "arabe": "مَلْعُون", "francais": "Maudit" },
  { "arabe": "جَدِيد", "francais": "Nouveau" },
  { "arabe": "قَدِيم", "francais": "Ancien" },
  { "arabe": "بَعِيد", "francais": "Lointain" },
  { "arabe": "قَرِيب", "francais": "Proche" },
  { "arabe": "عَالٍ", "francais": "Haut / Élevé" },
  { "arabe": "سَافِل", "francais": "Bas" },
  { "arabe": "مُسْتَقِيم", "francais": "Droit" },
  { "arabe": "مُعْوَجّ", "francais": "Tordu" },
    { "arabe": "مُسْتَقَرّ", "francais": "Lieu de séjour" },
  { "arabe": "مُسْتَوْدَع", "francais": "Lieu de dépôt" },
  { "arabe": "مُسْتَحِقّ", "francais": "Méritant" },
  { "arabe": "مُسْتَور", "francais": "Caché" },
  { "arabe": "مُسْتَمِرّ", "francais": "Continu" },
  { "arabe": "مُسْتَطِير", "francais": "Éclatant / Éparpillé" },
  { "arabe": "مُسْتَقِيم", "francais": "Droit" },
  { "arabe": "مُسْتَكْبِر", "francais": "Orgueilleux" },
  { "arabe": "مُسْتَضْعَف", "francais": "Opprimé" },
  { "arabe": "مُسْتَغْفِر", "francais": "Demandeur de pardon" },
  { "arabe": "مُسْتَبْشِر", "francais": "Réjoui" },
  { "arabe": "مُسْتَنِد", "francais": "Appuyé" },
  { "arabe": "مُسْتَوْقِد", "francais": "Attisant (le feu)" },
  { "arabe": "مُسْرِف", "francais": "Outrancier" },
  { "arabe": "مُتْرَف", "francais": "Vivant dans le luxe" },
  { "arabe": "مُجْرِم", "francais": "Criminel" },
  { "arabe": "مُخْلِص", "francais": "Sincère" },
  { "arabe": "مُخْبِت", "francais": "Humble" },
  { "arabe": "مُنِيب", "francais": "Repentant" },
  { "arabe": "مُقْسِط", "francais": "Équitable" },
    //---Parties du corps et Nature humaine--- 
   { "arabe": "وَجْه", "francais": "Visage" },
  { "arabe": "عَيْن", "francais": "Œil / Source" },
  { "arabe": "لِسَان", "francais": "Langue" },
  { "arabe": "شَفَة", "francais": "Lèvre" },
  { "arabe": "أُذُن", "francais": "Oreille" },
  { "arabe": "يَد", "francais": "Main" },
  { "arabe": "رِجْل", "francais": "Pied" },
  { "arabe": "ظَهْر", "francais": "Dos" },
  { "arabe": "بَطْن", "francais": "Ventre" },
  { "arabe": "رَأْس", "francais": "Tête" },
  { "arabe": "شَعْر", "francais": "Cheveu / Poil" },
  { "arabe": "جِلْد", "francais": "Peau" },
  { "arabe": "عَظْم", "francais": "Os" },
  { "arabe": "دَم", "francais": "Sang" },
  { "arabe": "لَحْم", "francais": "Viande / Chair" },
  { "arabe": "أَصَابِع", "francais": "Doigts" },
  { "arabe": "صَدْر", "francais": "Poitrine" },
  { "arabe": "كَبِد", "francais": "Peine / Foie" },
  { "arabe": "حَنْجَرَة", "francais": "Gorge" },
  { "arabe": "نَاصِيَة", "francais": "Front / Toupet" },
   //---Vie Sociale, Métiers et Objets---
   { "arabe": "مَلِك", "francais": "Roi" },
  { "arabe": "وَزِير", "francais": "Ministre / Aide" },
  { "arabe": "جُنُود", "francais": "Soldats / Armées" },
  { "arabe": "صَاحِب", "francais": "Compagnon" },
  { "arabe": "جَار", "francais": "Voisin" },
  { "arabe": "ضَيْف", "francais": "Invité" },
  { "arabe": "يَتِيم", "francais": "Orphelin" },
  { "arabe": "مِسْكِين", "francais": "Pauvre / Indigent" },
  { "arabe": "سَبِيل", "francais": "Chemin / Voie" },
  { "arabe": "قَرْيَة", "francais": "Village" },
  { "arabe": "مَدِينَة", "francais": "Ville" },
  { "arabe": "سُوق", "francais": "Marché" },
  { "arabe": "بَاب", "francais": "Porte" },
  { "arabe": "مِفْتَاح", "francais": "Clé" },
  { "arabe": "كُرْسِيّ", "francais": "Chaise / Siège" },
  { "arabe": "فِرَاش", "francais": "Lit / Tapis" },
  { "arabe": "ثَوْب", "francais": "Habit" },
  { "arabe": "حِيَل", "francais": "Ruses" },
  { "arabe": "قَلَم", "francais": "Plume / Stylo" },
  { "arabe": "قِرْطَاس", "francais": "Papier / Parchemin" },
      //---Animaux et Créatures---
   { "arabe": "غَنَم", "francais": "Moutons / Brebis" },
  { "arabe": "بَقَرَة", "francais": "Vache" },
  { "arabe": "إِبِل", "francais": "Chameaux" },
  { "arabe": "عِجْل", "francais": "Veau" },
  { "arabe": "كَلْب", "francais": "Chien" },
  { "arabe": "حِمَار", "francais": "Âne" },
  { "arabe": "غُرَاب", "francais": "Corbeau" },
  { "arabe": "هُدْهُد", "francais": "Huppe" },
  { "arabe": "نَمْلَة", "francais": "Fourmi" },
  { "arabe": "نَحْلَة", "francais": "Abeille" },
  { "arabe": "عَنْكَبُوت", "francais": "Araignée" },
  { "arabe": "حُوت", "francais": "Poisson / Baleine" },
  { "arabe": "فِيل", "francais": "Éléphant" },
  { "arabe": "طَيْر", "francais": "Oiseau" },
  { "arabe": "جَرَاد", "francais": "Sauterelles" },
  { "arabe": "قُمَّل", "francais": "Poux" },
  { "arabe": "ضَفَادِع", "francais": "Grenouilles" },
  { "arabe": "ثُعْبَان", "francais": "Serpent" },
  { "arabe": "أَسَد", "francais": "Lion" },
  { "arabe": "ذِئْب", "francais": "Loup" },
    //---Matériaux, Minéraux et Vêtements---
   { "arabe": "حَدِيد", "francais": "Fer" },
  { "arabe": "نُحَاس", "francais": "Cuivre / Airain" },
  { "arabe": "فِضَّة", "francais": "Argent (métal)" },
  { "arabe": "إِسْتَبْرَق", "francais": "Brocant / Soie épaisse" },
  { "arabe": "سُنْدُس", "francais": "Satin / Soie fine" },
  { "arabe": "حُلِيّ", "francais": "Parures / Bijoux" },
  { "arabe": "لُؤْلُؤ", "francais": "Perles" },
  { "arabe": "مَرْجَان", "francais": "Corail" },
  { "arabe": "فَخَّار", "francais": "Argile cuite / Poterie" },
  { "arabe": "زُجَاجَة", "francais": "Verre / Cristal" },
  { "arabe": "صُوف", "francais": "Laine" },
  { "arabe": "وَبَر", "francais": "Poil de chameau" },
  { "arabe": "جُلُود", "francais": "Peaux / Cuirs" },
  { "arabe": "قَطِرَان", "francais": "Goudron" },
  { "arabe": "خَشَب", "francais": "Bois" },
    //---Géographie et Phénomènes Naturels---
   { "arabe": "بُقْعَة", "francais": "Lieu / Endroit" },
  { "arabe": "كَثِيب", "francais": "Dune de sable" },
  { "arabe": "جُرُز", "francais": "Terre aride / stérile" },
  { "arabe": "صَعِيد", "francais": "Sol / Surface de la terre" },
  { "arabe": "فَجّ", "francais": "Col / Chemin entre deux montagnes" },
  { "arabe": "بَرْق", "francais": "Éclair" },
  { "arabe": "رَعْد", "francais": "Tonnerre" },
  { "arabe": "بَرَد", "francais": "Grêle" },
  { "arabe": "طُوفَان", "francais": "Déluge / Inondation" },
  { "arabe": "أكمام", "francais": "Enveloppes (de fruits)" },
  { "arabe": "حَبّ", "francais": "Graines" },
  { "arabe": "عَصْف", "francais": "Paille / Balle du grain" },
  { "arabe": "رَيْحَان", "francais": "Plantes aromatiques" },
      //---Verbes d'Action et Cognition---
   { "arabe": "يَتَفَكَّرُونَ", "francais": "Ils réfléchissent" },
  { "arabe": "يَعْقِلُونَ", "francais": "Ils raisonnent" },
  { "arabe": "يَبْصُرُونَ", "francais": "Ils voient / observent" },
  { "arabe": "يَسْمَعُونَ", "francais": "Ils entendent" },
  { "arabe": "يُوقِنُونَ", "francais": "Ils croient fermement" },
  { "arabe": "يَتَذَكَّرُونَ", "francais": "Ils se rappellent" },
  { "arabe": "يَخَافُونَ", "francais": "Ils redoutent" },
  { "arabe": "يَرْجُونَ", "francais": "Ils espèrent" },
  { "arabe": "يَسْتَغْفِرُونَ", "francais": "Ils demandent pardon" },
  { "arabe": "يَتَوَكَّلُونَ", "francais": "Ils s'en remettent (à Dieu)" },
    { "arabe": "يَنْظُرُونَ", "francais": "Ils regardent" },
  { "arabe": "يَعْلَمُونَ", "francais": "Ils savent" },
  { "arabe": "يَشْعُرُونَ", "francais": "Ils perçoivent" },
  { "arabe": "يَفْعَلُونَ", "francais": "Ils font" },
  { "arabe": "يَكْسِبُونَ", "francais": "Ils acquièrent" },
  { "arabe": "يَنْصُرُونَ", "francais": "Ils secourent" },
  { "arabe": "يَرْجِعُونَ", "francais": "Ils reviennent" },
  { "arabe": "يَضْحَكُونَ", "francais": "Ils rient" },
  { "arabe": "يَبْكُونَ", "francais": "Ils pleurent" },
  { "arabe": "يَسْجُدُونَ", "francais": "Ils se prosternent" },
  { "arabe": "يُنْفِقُونَ", "francais": "Ils dépensent" },
  { "arabe": "يُكَذِّبُونَ", "francais": "Ils démentent" },
  { "arabe": "يَقْتُلُونَ", "francais": "Ils tuent" },
  { "arabe": "يَخْرُجُونَ", "francais": "Ils sortent" },
  { "arabe": "يَدْخُلُونَ", "francais": "Ils entrent" },
  { "arabe": "يَسْتَعْجِلُونَ", "francais": "Ils hâtent" },
  { "arabe": "يَسْتَهْزِئُونَ", "francais": "Ils se moquent" },
  { "arabe": "يَخْتَصِمُونَ", "francais": "Ils se querellent" },
  { "arabe": "يَعْتَدُونَ", "francais": "Ils transgressent" },
  { "arabe": "يَفْسُقُونَ", "francais": "Ils désobéissent" },
  { "arabe": "يَمْكُرُونَ", "francais": "Ils complotent" },
  { "arabe": "يَهْتَدُونَ", "francais": "Ils se guident" },
  { "arabe": "يُبْصِرُونَ", "francais": "Ils voient clair" },
  { "arabe": "يُؤْمِنُونَ", "francais": "Ils croient" },
  { "arabe": "يَتَّقُونَ", "francais": "Ils craignent Dieu" },
     //---Vie Quotidienne et Maison---
   { "arabe": "أَثَاث", "francais": "Mobilier" },
  { "arabe": "مَتَاع", "francais": "Jouissance / Biens" },
  { "arabe": "آنِيَة", "francais": "Récipients / Vaiselle" },
  { "arabe": "أَكْوَاب", "francais": "Gobelets" },
  { "arabe": "نَمَارِق", "francais": "Coussins" },
  { "arabe": "زَرَابِيّ", "francais": "Tapis" },
  { "arabe": "أباريق", "francais": "Aiguières / Carafes" },
  { "arabe": "مِهَاد", "francais": "Berceau / Couche" },
  { "arabe": "سَقْف", "francais": "Toit / Plafond" },
  { "arabe": "بنيان", "francais": "Édifice / Construction" },
  { "arabe": "جِدَار", "francais": "Mur" },
  { "arabe": "كَنْز", "francais": "Trésor" },
  { "arabe": "سِرَاج", "francais": "Lampe" },
     //---Objets et Détails de la Nature---
   { "arabe": "فِرَاش", "francais": "Tapis / Couche" },
  { "arabe": "بِنَاء", "francais": "Édifice" },
  { "arabe": "مِهَاد", "francais": "Berceau" },
  { "arabe": "أَوْتَاد", "francais": "Pieux (montagnes)" },
  { "arabe": "أَزْوَاج", "francais": "Paires / Couples" },
  { "arabe": "سُبَات", "francais": "Repos" },
  { "arabe": "لِبَاس", "francais": "Vêtement" },
  { "arabe": "مَعَاش", "francais": "Gagne-pain" },
  { "arabe": "سِرَاج", "francais": "Flambeau" },
  { "arabe": "وَهَّاج", "francais": "Ardent" },
  { "arabe": "مُعْصِرَات", "francais": "Nuages pluvieux" },
  { "arabe": "ثَجَّاج", "francais": "Versante (eau)" },
  { "arabe": "حَبّ", "francais": "Grains" },
  { "arabe": "نَبَات", "francais": "Végétation" },
  { "arabe": "جَنَّات", "francais": "Jardins" },
  { "arabe": "أَلْفَاف", "francais": "Luxuriants" },
  { "arabe": "مِيقَات", "francais": "Terme fixé" },
  { "arabe": "صُور", "francais": "Trompe" },
  { "arabe": "أَفْوَاج", "francais": "Foules" },
  { "arabe": "أَبْوَاب", "francais": "Portes" },
  { "arabe": "سَرَاب", "francais": "Mirage" },
  { "arabe": "مِرْصَاد", "francais": "Guet" },
  { "arabe": "مَآب", "francais": "Refuge" },
  { "arabe": "أَحْقَاب", "francais": "Des siècles" },
  { "arabe": "بَرْد", "francais": "Fraicheur" },
    //---Les Actions du Cœur et de l'Esprit---
   { "arabe": "يَتَدَبَّرُونَ", "francais": "Ils méditent profondément" },
  { "arabe": "يَسْتَبْشِرُونَ", "francais": "Ils se réjouissent" },
  { "arabe": "يَتَضَرَّعُونَ", "francais": "Ils supplient humblement" },
  { "arabe": "يَسْتَكْبِرُونَ", "francais": "Ils s'enorgueillissent" },
  { "arabe": "يَعْتَرِفُونَ", "francais": "Ils reconnaissent (leurs fautes)" },
  { "arabe": "يَتَوَلَّوْنَ", "francais": "Ils se détournent" },
  { "arabe": "يَبْتَغُونَ", "francais": "Ils recherchent / aspirent" },
  { "arabe": "يَخْشَوْنَ", "francais": "Ils craignent (avec respect)" },
  { "arabe": "يَطْمَعُونَ", "francais": "Ils convoitent / espèrent" },
  { "arabe": "يَمْحَقُ", "francais": "Il anéantit / réduit à néant" },
  { "arabe": "يُرْبِي", "francais": "Il fait fructifier" },
  { "arabe": "يُضِلُّ", "francais": "Il égare" },
  { "arabe": "يَهْدِي", "francais": "Il guide" },
  { "arabe": "يَشْرَحُ", "francais": "Il épanouit / ouvre (la poitrine)" },
  { "arabe": "يَخْتِمُ", "francais": "Il scelle" },
    //---Nature, Agriculture et Phénomènes---
   { "arabe": "حَصِيد", "francais": "Moissonné / Rasé" },
  { "arabe": "خَاوِيَة", "francais": "Dépeuplée / En ruines" },
  { "arabe": "مُنْهَمِر", "francais": "Torrentiel (eau)" },
  { "arabe": "مُنْشَآت", "francais": "Vaisseaux élevés (navires)" },
  { "arabe": "جَوَارِ", "francais": "Vaisseaux qui voguent" },
  { "arabe": "أَعْلَام", "francais": "Montagnes / Signes" },
  { "arabe": "رُكَام", "francais": "Amoncellement (nuages)" },
  { "arabe": "وَدْق", "francais": "Pluie fine / Gouttes" },
  { "arabe": "سَنَا", "francais": "Éclat / Lueur" },
  { "arabe": "بَرَد", "francais": "Grêle" },
  { "arabe": "رَوَاسِي", "francais": "Montagnes fermement ancrées" },
  { "arabe": "سُبُل", "francais": "Chemins / Sentiers" },
  { "arabe": "فِجَاج", "francais": "Larges voies" },
  { "arabe": "أَنْهَار", "francais": "Rivières / Fleuves" },
  { "arabe": "يَنَابِيع", "francais": "Sources d'eau" },
    //---Anatomie et Développement Humain---
   { "arabe": "صُلْب", "francais": "Colonne vertébrale" },
  { "arabe": "تَرَائِب", "francais": "Os de la poitrine" },
  { "arabe": "أَمْشَاج", "francais": "Mélanges (fluides)" },
  { "arabe": "أَجِنَّة", "francais": "Fœtus (pluriel)" },
  { "arabe": "أَرْحَام", "francais": "Utérus / Matrices" },
  { "arabe": "مُضْغَة", "francais": "Chaire mâchée" },
  { "arabe": "عِظَام", "francais": "Os" },
  { "arabe": "أَطْوَار", "francais": "Phases / Étapes" },
  { "arabe": "نُطْفَة", "francais": "Goutte de sperme" },
  { "arabe": "عَلَقَة", "francais": "Adhérence / Sang coagulé" },
    //---Vie Sociale et Termes Juridiques---
   { "arabe": "أَسْبَاب", "francais": "Moyens / Voies d'accès" },
  { "arabe": "أَوْزَار", "francais": "Fardeaux / Péchés" },
  { "arabe": "أَنْصَاب", "francais": "Pierres dressées (idoles)" },
  { "arabe": "أَزْلَام", "francais": "Flèches de divination" },
  { "arabe": "بَحِيرَة", "francais": "Chamelle aux oreilles fendues" },
  { "arabe": "سَائِبَة", "francais": "Bête en liberté (sacrée)" },
  { "arabe": "وَصِيلَة", "francais": "Bête accouplée (sacrée)" },
  { "arabe": "حَام", "francais": "Étalon protégé (sacré)" },
  { "arabe": "قَانِع", "francais": "Pauvre discret" },
  { "arabe": "مُعْتَرّ", "francais": "Pauvre nécessiteux" },
   //---Au-delà et Descriptions---
   { "arabe": "سِجِّين", "francais": "Registre des méchants" },
  { "arabe": "عِلِّيِّين", "francais": "Registre des bons" },
  { "arabe": "مَرْقُوم", "francais": "Inscrit / Marqué" },
  { "arabe": "تَسْنِيم", "francais": "Source élevée" },
  { "arabe": "مَخْتُوم", "francais": "Cacheté / Scellé" },
  { "arabe": "رَحِيق", "francais": "Nectar" },
  { "arabe": "أَبَارِيق", "francais": "Aiguières" },
  { "arabe": "غِلْمَان", "francais": "Jeunes serviteurs" },
  { "arabe": "مُخَلَّدُونَ", "francais": "Éternels" },
  { "arabe": "مَسْكُوب", "francais": "Qui coule (eau)" },
];
